// JLPT N2 真题库 — 言語知識 (Q1~47)
// 来源: 2024-07, 2022-07, 2025-07
// 总计: 150 题

const QUIZ_DATA_REAL = [
  {
    id: 1,
    level: "n2",
    type: "vocab_reading",
    question: "状況 を詳細に書いてください。",
    options: ["そうざい", "そうさい", "しょうざい", "しょうさい"],
    answer: 3,
    explanation: "N2真题2024-07 第1题",
    source: "2024-07",
  },
  {
    id: 2,
    level: "n2",
    type: "vocab_reading",
    question: "分析には少し時間がかかります。",
    options: ["ぶんせき", "ぶんかい", "ぶんせつ", "ぶんかつ"],
    answer: 0,
    explanation: "N2真题2024-07 第2题",
    source: "2024-07",
  },
  {
    id: 3,
    level: "n2",
    type: "vocab_reading",
    question: "髪の毛がくしに絡まってしまった。",
    options: ["はさまって", "からまって", "つまって", "たまって"],
    answer: 1,
    explanation: "N2真题2024-07 第3题",
    source: "2024-07",
  },
  {
    id: 4,
    level: "n2",
    type: "vocab_reading",
    question: "ここでは、農薬をまったく使わずに野菜を栽培している。",
    options: ["のんやく", "のうやく", "のうらく", "のんらく"],
    answer: 1,
    explanation: "N2真题2024-07 第4题",
    source: "2024-07",
  },
  {
    id: 5,
    level: "n2",
    type: "vocab_reading",
    question: "とても鮮やかだったことをよく覚えている。",
    options: ["おだやか", "さわやか", "あざやか", "なごやか"],
    answer: 2,
    explanation: "N2真题2024-07 第5题",
    source: "2024-07",
  },
  {
    id: 6,
    level: "n2",
    type: "kanji",
    question: "この会社をしぼうした理由を教えてください。",
    options: ["希望", "志望", "指望", "貴望"],
    answer: 0,
    explanation: "N2真题2024-07 第6题",
    source: "2024-07",
  },
  {
    id: 7,
    level: "n2",
    type: "kanji",
    question: "あの作家のたんぺん小説は、とても面白い。",
    options: ["短編", "単編", "短遍", "単遍"],
    answer: 1,
    explanation: "N2真题2024-07 第7题",
    source: "2024-07",
  },
  {
    id: 8,
    level: "n2",
    type: "kanji",
    question: "桜の花がちっていくのを眺める。",
    options: ["消って", "去って", "散って", "失って"],
    answer: 2,
    explanation: "N2真题2024-07 第8题",
    source: "2024-07",
  },
  {
    id: 9,
    level: "n2",
    type: "kanji",
    question: "このセーターにはとてもやわらかい毛糸が使われている。",
    options: ["伸らかい", "軽らかい", "暖らかい", "柔らかい"],
    answer: 3,
    explanation: "N2真题2024-07 第9题",
    source: "2024-07",
  },
  {
    id: 10,
    level: "n2",
    type: "kanji",
    question: "最近あまり体調がよくないのは、ひろうのせいだろう。",
    options: ["疲労", "病労", "疲老", "病老"],
    answer: 0,
    explanation: "N2真题2024-07 第10题",
    source: "2024-07",
  },
  {
    id: 11,
    level: "n2",
    type: "vocab_fill",
    question: "しょうゆの（ ）原料は大豆です。",
    options: ["主", "要", "正", "本"],
    answer: 1,
    explanation: "N2真题2024-07 第11题",
    source: "2024-07",
  },
  {
    id: 12,
    level: "n2",
    type: "vocab_fill",
    question: "子どもたちの読書（ ）が進んでいるらしい。",
    options: ["抜け", "逃げ", "別れ", "離れ"],
    answer: 3,
    explanation: "N2真题2024-07 第12题",
    source: "2024-07",
  },
  {
    id: 13,
    level: "n2",
    type: "vocab_fill",
    question: "経営の方針については、社長が決定（ ）を持っている。",
    options: ["任", "手", "権", "裁"],
    answer: 3,
    explanation: "N2真题2024-07 第13题",
    source: "2024-07",
  },
  {
    id: 14,
    level: "n2",
    type: "vocab_context",
    question: "両親はおいしい料理で客を（ ）のが好きだ。",
    options: ["もてなす", "おだてる", "許す", "救う"],
    answer: 0,
    explanation: "N2真题2024-07 第14题",
    source: "2024-07",
  },
  {
    id: 15,
    level: "n2",
    type: "vocab_context",
    question: "その駅は、各駅停車の電車は止まりますが、急行電車は（ ）します。",
    options: ["経由", "直進", "通過", "横断"],
    answer: 2,
    explanation: "N2真题2024-07 第15题",
    source: "2024-07",
  },
  {
    id: 16,
    level: "n2",
    type: "vocab_context",
    question: "見た人の記憶に残るような（ ）のあるポスターにしたい。",
    options: ["インパクト", "プレッシャー", "チャージ", "ショック"],
    answer: 0,
    explanation: "N2真题2024-07 第16题",
    source: "2024-07",
  },
  {
    id: 17,
    level: "n2",
    type: "vocab_context",
    question: "地元の選手がオリンピックでメダルを獲得したことがテレビで（ ）され た。",
    options: ["通信", "普及", "伝言", "報道"],
    answer: 3,
    explanation: "N2真题2024-07 第17题",
    source: "2024-07",
  },
  {
    id: 18,
    level: "n2",
    type: "vocab_context",
    question: "台風で電車が運休になり、通勤や通学で利用する人に（ ）影響を与え た。",
    options: ["大まかな", "偉大な", "大げさな", "多大な"],
    answer: 3,
    explanation: "N2真题2024-07 第18题",
    source: "2024-07",
  },
  {
    id: 19,
    level: "n2",
    type: "vocab_context",
    question: "西川さんは転校してきたばかりだが、友達もできて、もうすっかりクラスに （ ）いる。",
    options: ["当てはまって", "溶け込んで", "結びついて", "触れ合って"],
    answer: 1,
    explanation: "N2真题2024-07 第19题",
    source: "2024-07",
  },
  {
    id: 20,
    level: "n2",
    type: "vocab_context",
    question: "私は（ ）性格なので、時々財布を持たずに買い物に出かけてしまうこと がある。",
    options: ["あつかましい", "うっとうしい", "そそっかしい", "さわがしい"],
    answer: 2,
    explanation: "N2真题2024-07 第20题",
    source: "2024-07",
  },
  {
    id: 21,
    level: "n2",
    type: "meaning",
    question: "出張の日程はおおよそ決まりました。",
    options: ["だいたい", "すべて", "やっと", "もう"],
    answer: 0,
    explanation: "N2真题2024-07 第21题",
    source: "2024-07",
  },
  {
    id: 22,
    level: "n2",
    type: "meaning",
    question: "彼女はとても行儀がいい。",
    options: ["アイデア", "サービス", "マナー", "イメージ"],
    answer: 2,
    explanation: "N2真题2024-07 第22题",
    source: "2024-07",
  },
  {
    id: 23,
    level: "n2",
    type: "meaning",
    question: "中西さんはいつもいばっている。",
    options: ["眠そうにして", "偉そうにして", "暇そうにして", "嫌そうにして"],
    answer: 1,
    explanation: "N2真题2024-07 第23题",
    source: "2024-07",
  },
  {
    id: 24,
    level: "n2",
    type: "meaning",
    question: "使わない物は、ここに収納してください。",
    options: ["並べて", "捨てて", "預けて", "しまって"],
    answer: 3,
    explanation: "N2真题2024-07 第24题",
    source: "2024-07",
  },
  {
    id: 25,
    level: "n2",
    type: "meaning",
    question: "横山さんは不平を言うことが多い。",
    options: ["冗談", "文句", "うそ", "わがまま"],
    answer: 1,
    explanation: "N2真题2024-07 第25题",
    source: "2024-07",
  },
  {
    id: 26,
    level: "n2",
    type: "usage",
    question: "共有",
    options: ["市民ボランティアの共有で、留学生のスピーチコンテストが行われた。", "大学と企業が共有で新しい技術の研究を行っている。", "これらの事件には、発生場所に共有の特徴があることが分かった。", "結婚してから購入した物は、夫婦の共有の財産になる。"],
    answer: 3,
    explanation: "N2真题2024-07 第26题",
    source: "2024-07",
  },
  {
    id: 27,
    level: "n2",
    type: "usage",
    question: "鋭い",
    options: ["動物たちが自然界で生きていくためには、鋭い感覚が必要だ。", "弟は記憶が鋭くて、本に載っているたくさんの国名や国旗をすぐに覚えた。", "赤ちゃんの肌は鋭いから、少しの刺激で赤くなってしまう。", "運動の能力が鋭い人は、どんなスポーツでもすぐに上達する。"],
    answer: 0,
    explanation: "N2真题2024-07 第27题",
    source: "2024-07",
  },
  {
    id: 28,
    level: "n2",
    type: "usage",
    question: "はきはき",
    options: ["よく眠ったので、今日は頭がはきはきとしている。", "ビルの屋上から、遠くの山がはきはきと見える。", "その学生は、聞かれたことにはきはきと答えた。", "ミスの原因をはきはきとさせるために、調査が行われた。"],
    answer: 2,
    explanation: "N2真题2024-07 第28题",
    source: "2024-07",
  },
  {
    id: 29,
    level: "n2",
    type: "usage",
    question: "鑑賞",
    options: ["学校の授業で、工場へ行って自動車を組み立てる様子を鑑賞した。", "中学生のとき、市のコンサートホールでクラシック音楽を鑑賞した。", "資料を読んで、自然を守るための国の活動について鑑賞した。", "レストランで、素材の良さを生かした料理を舌でじっくり鑑賞した。"],
    answer: 1,
    explanation: "N2真题2024-07 第29题",
    source: "2024-07",
  },
  {
    id: 30,
    level: "n2",
    type: "usage",
    question: "着々",
    options: ["ベランダが着々と古くなって危険なので、修理することにした。", "ゲームに夢中になっていたら、時間が着々とたっていた。", "来週のパーティーの準備は着々と進んでいるようだ。", "夕方になって、外は着々と涼しくなって生きている。"],
    answer: 2,
    explanation: "N2真题2024-07 第30题",
    source: "2024-07",
  },
  {
    id: 31,
    level: "n2",
    type: "grammar",
    question: "卓球 クラブの山谷さんは大きな大会で何度も優勝しているのに、「私（ ）まだまだですよ。」といつも言っている。",
    options: ["まで", "さえ", "ばかり", "なんか"],
    answer: 2,
    explanation: "N2真题2024-07 第31题",
    source: "2024-07",
  },
  {
    id: 32,
    level: "n2",
    type: "grammar",
    question: "携帯電話を一人一台持つのが当たり前といわれる現代で、私のように携帯電 話なしで生活している人は（ ）いるのだろうか。",
    options: ["どうも", "どれほど", "どうしても", "どんなに"],
    answer: 3,
    explanation: "N2真题2024-07 第32题",
    source: "2024-07",
  },
  {
    id: 33,
    level: "n2",
    type: "grammar",
    question: "花山市では、きゅうりやトマト、なす（ ）夏の野菜が多く生産されて いる。",
    options: ["とする", "に関する", "といった", "に沿った"],
    answer: 0,
    explanation: "N2真题2024-07 第33题",
    source: "2024-07",
  },
  {
    id: 34,
    level: "n2",
    type: "grammar",
    question: "彼とは数年前に先輩の結婚式で（ ）、ずっと会っていない。",
    options: ["会ったきり", "会ったばかりか", "会っただけに", "会ったところ"],
    answer: 2,
    explanation: "N2真题2024-07 第34题",
    source: "2024-07",
  },
  {
    id: 35,
    level: "n2",
    type: "grammar",
    question: "近所に子供向けのダンススクールができるらしい。オープンしたら、娘を体 験レッスンに（ ）と思っている。",
    options: ["参加してみようか", "参加させてみようか", "参加してみてよかった", "参加させてみてよかった"],
    answer: 1,
    explanation: "N2真题2024-07 第35题",
    source: "2024-07",
  },
  {
    id: 36,
    level: "n2",
    type: "grammar",
    question: "（カメラ屋で） 客「カメラを海に落としてしまって、電源が入らないんです。中に水が入っ てしまったようなのですが······。」 店員「海水が入った（ ）、修理は難しいかもしれませんが、一応見てみ ますね。」",
    options: ["のであれば", "ことであれば", "のであって", "ことであって"],
    answer: 3,
    explanation: "N2真题2024-07 第36题",
    source: "2024-07",
  },
  {
    id: 37,
    level: "n2",
    type: "grammar",
    question: "母「引っ越しまでまだ時間はあるけど、直前になって慌てないように、（ ）、荷物の整理、進めておきなさいね。」 息子「うん、わかった。」",
    options: ["少しだけでいいのに", "少しだけならよくても", "少しずつでいいから", "少しずつならよくて"],
    answer: 2,
    explanation: "N2真题2024-07 第37题",
    source: "2024-07",
  },
  {
    id: 38,
    level: "n2",
    type: "grammar",
    question: "1896年の第1回オリンピックに参加した国と地域の数は14だったが、2004年には200を超える（ ）。",
    options: ["べきだった", "つもりだった", "ほかなかった", "までになった"],
    answer: 0,
    explanation: "N2真题2024-07 第38题",
    source: "2024-07",
  },
  {
    id: 39,
    level: "n2",
    type: "grammar",
    question: "チームでの仕事をスムーズに進めるには、メンバー同士の十分なコミュニケ ーション( )。",
    options: ["にすぎない", "が欠かせない", "のおかげだ", "とのことだ"],
    answer: 3,
    explanation: "N2真题2024-07 第39题",
    source: "2024-07",
  },
  {
    id: 40,
    level: "n2",
    type: "grammar",
    question: "昨日、新しくできた遊園地に行った。電車より車のほうが早いだろうと思って車で行ったら、ひどい渋滞でかえって時間がかかってしまった。やはり電車で( )。",
    options: ["行けばよかった", "行くはずだった", "行かなくて済んだ", "行きたくてしかたがなかった"],
    answer: 0,
    explanation: "N2真题2024-07 第40题",
    source: "2024-07",
  },
  {
    id: 41,
    level: "n2",
    type: "grammar",
    question: "2時間の通勤を週に5日、40年間続けたとすると、通勤時間は約2万時間で、2年以上の時間を通勤に使う（ ）。",
    options: ["ということにする", "ということにしている", "ということになる", "ということになっている"],
    answer: 2,
    explanation: "N2真题2024-07 第41题",
    source: "2024-07",
  },
  {
    id: 42,
    level: "n2",
    type: "grammar",
    question: "（電話で） A「お電話ありがとうございます。クロカワ建設営業課でございます。」B「高橋さんはいらっしゃいますか。」 A「失礼ですが、お名前を（ ）。」",
    options: ["伺ったらいかがでしょうか", "伺ってもよろしいでしょうか", "お伝えしたらいかがでしょうか", "お伝えしてもよろしいでしょう"],
    answer: 1,
    explanation: "N2真题2024-07 第42题",
    source: "2024-07",
  },
  {
    id: 43,
    level: "n2",
    type: "grammar_fill",
    question: "「さわら」という魚は、漢字で「鰆」と書く ★ 魚の 一つです。",
    options: ["ように", "わかる", "ことから", "春を代表する"],
    answer: 3,
    explanation: "N2真题2024-07 第43题",
    source: "2024-07",
  },
  {
    id: 44,
    level: "n2",
    type: "grammar_fill",
    question: "会議での西山さんのプレゼンは、普段はなかなか ★ 素 晴らしかった。",
    options: ["ぐらい", "部長が", "褒める", "褒めることがない"],
    answer: 1,
    explanation: "N2真题2024-07 第44题",
    source: "2024-07",
  },
  {
    id: 45,
    level: "n2",
    type: "grammar_fill",
    question: "同じ高温 ★ は大きく変わる。",
    options: ["感じ方", "でも", "温度や風の強さなど", "によって"],
    answer: 3,
    explanation: "N2真题2024-07 第45题",
    source: "2024-07",
  },
  {
    id: 46,
    level: "n2",
    type: "grammar_fill",
    question: "「山川大学アニメ研究会」は、 ★ できた団体です。",
    options: ["学生が", "集まって", "アニメが", "好きでたまらないという"],
    answer: 2,
    explanation: "N2真题2024-07 第46题",
    source: "2024-07",
  },
  {
    id: 47,
    level: "n2",
    type: "grammar_fill",
    question: "会社の今井先輩は、自分はミスが多いといつも言っているが、 ★ ように見える。",
    options: ["新人で", "何でも完璧にできている", "私からすると", "わからないことばかりの"],
    answer: 1,
    explanation: "N2真题2024-07 第47题",
    source: "2024-07",
  },
  {
    id: 48,
    level: "n2",
    type: "vocab_reading",
    question: "その当時の記憶はあまりない。",
    options: ["きりょく", "きよく", "きろく", "きおく"],
    answer: 3,
    explanation: "N2真题2022-07 第1题",
    source: "2022-07",
  },
  {
    id: 49,
    level: "n2",
    type: "vocab_reading",
    question: "前田さんがそんなに偉い人だとは知りませんでした。",
    options: ["かしこい", "えらい", "すごい", "するどい"],
    answer: 0,
    explanation: "N2真题2022-07 第2题",
    source: "2022-07",
  },
  {
    id: 50,
    level: "n2",
    type: "vocab_reading",
    question: "私が仕事の話を始めたら、途端に西川さんの機嫌が悪くなった。",
    options: ["とたんに", "よたんに", "とだんに", "とだんに"],
    answer: 1,
    explanation: "N2真题2022-07 第3题",
    source: "2022-07",
  },
  {
    id: 51,
    level: "n2",
    type: "vocab_reading",
    question: "スピーチ大会の司会を務める。",
    options: ["まとめる", "やめる", "やめる", "つとめる"],
    answer: 3,
    explanation: "N2真题2022-07 第4题",
    source: "2022-07",
  },
  {
    id: 52,
    level: "n2",
    type: "vocab_reading",
    question: "これは特別な素材で作られているそうだ。",
    options: ["そうざい", "すさい", "そざい", "すうざい"],
    answer: 2,
    explanation: "N2真题2022-07 第5题",
    source: "2022-07",
  },
  {
    id: 53,
    level: "n2",
    type: "kanji",
    question: "いつのまにか太陽がのぼっていた。",
    options: ["おって", "昇って", "昇って", "照って"],
    answer: 2,
    explanation: "N2真题2022-07 第6题",
    source: "2022-07",
  },
  {
    id: 54,
    level: "n2",
    type: "kanji",
    question: "すいちょくに線を引く。",
    options: ["乗頂", "乗直", "垂頂", "垂直"],
    answer: 3,
    explanation: "N2真题2022-07 第7题",
    source: "2022-07",
  },
  {
    id: 55,
    level: "n2",
    type: "kanji",
    question: "研修⽣を受け⼊れるためには、じゅうきょを確保する必要がある。",
    options: [".住宅", ".住居", ".住家", ".住屋"],
    answer: 1,
    explanation: "N2真题2022-07 第8题",
    source: "2022-07",
  },
  {
    id: 56,
    level: "n2",
    type: "kanji",
    question: "災害にそなえることはとても⼤切だ。",
    options: [".備える", ".準える", ".策える", ".防える １０.てんけいてきな例を挙げて説明した。 1.点形的 2.典形的 3.点型的 4.典型的 問題3（ ）に⼊れるのに最もよいものを１・２・３・４から⼀つ選びなさい。 11.( )分野の⼈と話すのはいい刺激になる。 1.逆 2.異 3.副 4.裏 12.その店は、よい品物を（ ）価格で売っている。"],
    answer: 3,
    explanation: "N2真题2022-07 第9题",
    source: "2022-07",
  },
  {
    id: 57,
    level: "n2",
    type: "kanji",
    question: "てんけいてきな例を挙げて説明した。",
    options: ["点形的", "典形的", "点型的", "典型的"],
    answer: 3,
    explanation: "N2真题2022-07 第10题",
    source: "2022-07",
  },
  {
    id: 58,
    level: "n2",
    type: "vocab_fill",
    question: "( )分野の⼈と話すのはいい刺激になる。",
    options: [".逆", ".異", ".副", ".裏"],
    answer: 1,
    explanation: "N2真题2022-07 第11题",
    source: "2022-07",
  },
  {
    id: 59,
    level: "n2",
    type: "vocab_fill",
    question: "その店は、よい品物を（ ）価格で売っている。",
    options: [".半", ".安", ".⼩", ".低"],
    answer: 3,
    explanation: "N2真题2022-07 第12题",
    source: "2022-07",
  },
  {
    id: 60,
    level: "n2",
    type: "vocab_fill",
    question: "運転免許証なと、顔写真( )の⾝分証明書を⾒せてください。",
    options: [".⾜し", ".載せ", ".付き", ".含み 3 問題4（ ）に⼊れるのに最もよいものを１・２・３・４から⼀つ選びなさい。"],
    answer: 2,
    explanation: "N2真题2022-07 第13题",
    source: "2022-07",
  },
  {
    id: 61,
    level: "n2",
    type: "vocab_context",
    question: "職場環境の問題については、会社との( )の結果、改善してもらえることになった。",
    options: [".交渉", ".授受", ".通話", ".出願"],
    answer: 0,
    explanation: "N2真题2022-07 第14题",
    source: "2022-07",
  },
  {
    id: 62,
    level: "n2",
    type: "vocab_context",
    question: "この企画を成功させるには、いくつもの課題を( )しなければならない。",
    options: [".キャンセル", ".クリア", ".カット", ".プッシュ"],
    answer: 1,
    explanation: "N2真题2022-07 第15题",
    source: "2022-07",
  },
  {
    id: 63,
    level: "n2",
    type: "vocab_context",
    question: "このカメラは⼩型だが、通常のモデルに⽐べて性能が( )いるわけではない。",
    options: [".縮んで", ".荒れて", ".沈んで", ".劣って"],
    answer: 3,
    explanation: "N2真题2022-07 第16题",
    source: "2022-07",
  },
  {
    id: 64,
    level: "n2",
    type: "vocab_context",
    question: "⽗は⼿術後、医者も驚くほど( )回復した。",
    options: [".劇的に", ".格別に", ".真剣に", ".強⼤に"],
    answer: 0,
    explanation: "N2真题2022-07 第17题",
    source: "2022-07",
  },
  {
    id: 65,
    level: "n2",
    type: "vocab_context",
    question: "このシスムを利⽤するには、インターネットに( )しているパソコが必要です。",
    options: [".到達", ".付属", ".接続", ".密着 19アルバイトの募集は3⽉末で( )ので、もう応募はできません。 1.取り払った 2.打ち消した 3.締め切った 4.引き離した 20.ガイドの後ろをツアー客たちが、( )ついて歩いている。 1.ごくごく 2.ぞろぞろ 3.ぎしぎし 4.じめじめ 問題5 の⾔葉に意味が最も近いものを１・２・３・４から⼀つ選びなさい。"],
    answer: 2,
    explanation: "N2真题2022-07 第18题",
    source: "2022-07",
  },
  {
    id: 66,
    level: "n2",
    type: "vocab_context",
    question: "アルバイトの募集は3月末で（ ）ので、もう応募はできません。",
    options: ["取り払った", "打ち消した", "締め切った", "引き離した"],
    answer: 2,
    explanation: "N2真题2022-07 第19题",
    source: "2022-07",
  },
  {
    id: 67,
    level: "n2",
    type: "vocab_context",
    question: "ガイドの後ろをツアー客たちが、( )ついて歩いている。",
    options: [".ごくごく", ".ぞろぞろ", ".ぎしぎし", ".じめじめ 問題5 の⾔葉に意味が最も近いものを１・２・３・４から⼀つ選びなさい。"],
    answer: 1,
    explanation: "N2真题2022-07 第20题",
    source: "2022-07",
  },
  {
    id: 68,
    level: "n2",
    type: "meaning",
    question: "衝突しそうになってしまった。",
    options: [".ぶつかりそう", ".落ちそう", ".壊しそう", ".破りそう"],
    answer: 0,
    explanation: "N2真题2022-07 第21题",
    source: "2022-07",
  },
  {
    id: 69,
    level: "n2",
    type: "meaning",
    question: "彼には再三お願いしているんです。",
    options: [".たまに", ".何度か", ".何度も", ".いつも"],
    answer: 2,
    explanation: "N2真题2022-07 第22题",
    source: "2022-07",
  },
  {
    id: 70,
    level: "n2",
    type: "meaning",
    question: "彼が⾔っていることはでたらめだ。",
    options: [".悪⼝", ".わがまま", ".うそ", ".⾃慢"],
    answer: 2,
    explanation: "N2真题2022-07 第23题",
    source: "2022-07",
  },
  {
    id: 71,
    level: "n2",
    type: "meaning",
    question: "すみません、お勘定をお願いします。",
    options: [".注⽂", ".会計", ".予約", ".配達"],
    answer: 1,
    explanation: "N2真题2022-07 第24题",
    source: "2022-07",
  },
  {
    id: 72,
    level: "n2",
    type: "meaning",
    question: "今⽇は、⽝がいつもよりさわがしい。",
    options: [".悲しそうだ", ".静かだ", ".楽しそうだ", ".うるさい 4 問題6 次の⾔葉の使い⽅として最もよいものを１・２・３・４から⼀つ選びなさい。"],
    answer: 3,
    explanation: "N2真题2022-07 第25题",
    source: "2022-07",
  },
  {
    id: 73,
    level: "n2",
    type: "usage",
    question: "温厚",
    options: [".温厚な伯⽗は、みんなから愛されている。", ".旅⾏中は、どこに⾏っても温厚な歓迎を受けてうれしかった。", ".今⽇は気温が下がるようなので、温厚なコートが必要だ。", ".雪の⽇には温厚なスープが飲みたくなる。"],
    answer: 0,
    explanation: "N2真题2022-07 第26题",
    source: "2022-07",
  },
  {
    id: 74,
    level: "n2",
    type: "usage",
    question: "濁る",
    options: [".外と室内の温度の差で窓が濁っている。", ".今⽇は空が雲で暗く濁っている。", ".しばらく洗っていないので、⾞が濁っている。", ".⼤⾬で川の⽔が茶⾊く濁っている。"],
    answer: 3,
    explanation: "N2真题2022-07 第27题",
    source: "2022-07",
  },
  {
    id: 75,
    level: "n2",
    type: "usage",
    question: "世代",
    options: ["野口さんはまだ20代なので、世代を取っているとはいえない。", "先日のパーティーでは私と同じ世代の人がたくさんいて、話が盛り上がった。", "青山さんは今は日本語の先生をしているが、実は英語の先生の世代が長い。", "仕事を頑張るだけでなく、趣味も楽しんで、充実した世代を送りたい。"],
    answer: 2,
    explanation: "N2真题2022-07 第28题",
    source: "2022-07",
  },
  {
    id: 76,
    level: "n2",
    type: "usage",
    question: "普及",
    options: [".よくないうわさが普及しているので、気をつけてください。", ".全員に飲み物が普及したようなので、森さんから乾杯のあいさつをお願いします", ".最近は携帯電話が普及しているので、家に電話を置かない家庭もある。", ".先週からインフルエンザが普及していて、⼩学校が休みになっている。"],
    answer: 3,
    explanation: "N2真题2022-07 第29题",
    source: "2022-07",
  },
  {
    id: 77,
    level: "n2",
    type: "usage",
    question: "⽣じる",
    options: [".メールシステムに問題が⽣じて、メールが送れなくなった。", ".バターやチーズは⽜乳から⽣じる。", ".昨⽇、姉に2番⽬の⼦どもが⽣じた。", ".いくら考えても、いいアイデアが⽣じない。 5 問題7（ ）に⼊れるのに最もよいものをから⼀つ選びなさい。"],
    answer: 0,
    explanation: "N2真题2022-07 第30题",
    source: "2022-07",
  },
  {
    id: 78,
    level: "n2",
    type: "grammar",
    question: "このカレーは15分（ ）あればできるので、よく作る。",
    options: ["に", "も", "まで", "より"],
    answer: 1,
    explanation: "N2真题2022-07 第31题",
    source: "2022-07",
  },
  {
    id: 79,
    level: "n2",
    type: "grammar",
    question: "A「新しい携帯電話ちょっと使いづらいんだよね。」 B「使っていれば( )慣れるよ。",
    options: [".いまにも", ".ようやく", ".そのうち", ".いつのまにか"],
    answer: 2,
    explanation: "N2真题2022-07 第32题",
    source: "2022-07",
  },
  {
    id: 80,
    level: "n2",
    type: "grammar",
    question: "今朝は寝坊してしまい、⾷事をする時間( )顔を洗う時間もなかった。",
    options: [".すら", ".しか", ".とはいえ", ".どころか"],
    answer: 3,
    explanation: "N2真题2022-07 第33题",
    source: "2022-07",
  },
  {
    id: 81,
    level: "n2",
    type: "grammar",
    question: "A「ねえ、経済学のレポート書けた?」 B「うん、難しかったけど、（ )書いたよ。）」",
    options: [".書けば", ".書いてでも", ".書くだけは", ".書いたわりに"],
    answer: 2,
    explanation: "N2真题2022-07 第34题",
    source: "2022-07",
  },
  {
    id: 82,
    level: "n2",
    type: "grammar",
    question: "情報技術の発展( )、コミュニケーションの⼿段は多様化している。",
    options: [".において", ".にこたえて", ".にあたって", ".にともなって"],
    answer: 3,
    explanation: "N2真题2022-07 第35题",
    source: "2022-07",
  },
  {
    id: 83,
    level: "n2",
    type: "grammar",
    question: "(⻭医者のホームページで) ⾍⻭が⼩さい( )、簡単な治療で済みます。⾍⻭かもしれないと思ったら、早めに受診す るようにしましょう。",
    options: [".うちなら", ".うちでも", ".だけなら", ".だけでも"],
    answer: 0,
    explanation: "N2真题2022-07 第36题",
    source: "2022-07",
  },
  {
    id: 84,
    level: "n2",
    type: "grammar",
    question: "A ⽔族館では、2 か⽉前にイルカの⾚ちゃんが⽣まれてから来場者が増え、⾮常に混雑 する( )、開館時間を早めることを検討している。",
    options: [".ようにしたとしても", ".ようにしたことから", ".ようになったとしても", ".ようになったことから"],
    answer: 3,
    explanation: "N2真题2022-07 第37题",
    source: "2022-07",
  },
  {
    id: 85,
    level: "n2",
    type: "grammar",
    question: "（ホテルで） 客「これから⻄森町に⾏くんですが、どこかおいしい和⾷のお店はありますか。」 フロント「⻄森町に（ ）『さくら』はいかがでしょうか。⼤変⼈気のあるお店です。」",
    options: [".伺うんでしたら", ".伺いますと", ".いらっしゃるんでしたら", ".いらっしゃいますと"],
    answer: 2,
    explanation: "N2真题2022-07 第38题",
    source: "2022-07",
  },
  {
    id: 86,
    level: "n2",
    type: "grammar",
    question: "⽥中さんは仕事が忙しいらしく、最近テニスクラブの復習を( )。",
    options: [".休みかねない", ".休みがちだ", ".休むとのことだ", ".休むに違いない"],
    answer: 3,
    explanation: "N2真题2022-07 第39题",
    source: "2022-07",
  },
  {
    id: 87,
    level: "n2",
    type: "grammar",
    question: "飼っている⽝が最近よくしゃっくりをする。⼼配になって病院で聞いてみたら、１時間 以上続く場合は検査したほうがいいが、すぐに⽌まるなら( )と⾔われた。",
    options: [".⼼配しなければならない", ".⼼配しないでもない", ".⼼配するわけではない", ".⼼配することはない"],
    answer: 0,
    explanation: "N2真题2022-07 第40题",
    source: "2022-07",
  },
  {
    id: 88,
    level: "n2",
    type: "grammar",
    question: "私が教えている経営学の講義では、去年から、毎回学⽣に講義の感想や質問を書いて ( )。そこから気づかされることも多いからだ。",
    options: [".出してもらうことにしている", ".出してもらうことがある", ".出してあげることにしている", ".出してあげることがある"],
    answer: 0,
    explanation: "N2真题2022-07 第41题",
    source: "2022-07",
  },
  {
    id: 89,
    level: "n2",
    type: "grammar",
    question: "A「ねえ、⼤変。これから⾏くお寺、⾒学するには( )よ。ガイドブックのここに書い てある。 B「本当だ。今から予約できるか電話して聞いてみようか。」",
    options: [".予約しないといけないみたいだ", ".予約しないといけないはずだ", ".予約したくなるみたいだ", ".予約したくなるはずだ 7 問題8 次の⽂の ★ に⼊る最もよいものを１・２・３・４から⼀つ選びなさい。"],
    answer: 2,
    explanation: "N2真题2022-07 第42题",
    source: "2022-07",
  },
  {
    id: 90,
    level: "n2",
    type: "grammar_fill",
    question: "この歌を聞く ★ ことだ。彼はカラオケに行くと必ずこの歌を歌っていた。",
    options: ["には", "思い出す", "たびに", "高校時代の友人の"],
    answer: 0,
    explanation: "N2真题2022-07 第43题",
    source: "2022-07",
  },
  {
    id: 91,
    level: "n2",
    type: "grammar_fill",
    question: "昨日、アルバイトに遅刻しそうだったので ★ 結局遅刻してしまった。",
    options: ["タクシーに乗ったら", "かえって時間がかり", "急ごうと思って", "道が渋滞していたせいで"],
    answer: 3,
    explanation: "N2真题2022-07 第44题",
    source: "2022-07",
  },
  {
    id: 92,
    level: "n2",
    type: "grammar_fill",
    question: "来月結婚する友人に結婚式のスピーチを頼まれた。大勢の前で話すのは ★ 飛び出していった。",
    options: ["悩んだのだが", "と言われて", "どうしても", "苦手なので"],
    answer: 2,
    explanation: "N2真题2022-07 第45题",
    source: "2022-07",
  },
  {
    id: 93,
    level: "n2",
    type: "grammar_fill",
    question: "先日の政治家A氏の発言はあまりに無責任だ。 ★ と思う。",
    options: ["政治家としての", "うえで", "発言しなければならなかった", "自分の立場をよく考えた"],
    answer: 1,
    explanation: "N2真题2022-07 第46题",
    source: "2022-07",
  },
  {
    id: 94,
    level: "n2",
    type: "grammar_fill",
    question: "食事や睡眠などの生活習慣は一度乱れてしまうと、 ★ 、大切だ。",
    options: ["規則正しい生活を", "戻そうとしても", "普段から意識することが", "なかなか戻せないので"],
    answer: 3,
    explanation: "N2真题2022-07 第47题",
    source: "2022-07",
  },
  {
    id: 1,
    level: "n2",
    type: "vocab_reading",
    question: "辛い食べ物は好きではありません。",
    options: ["あまい", "からい", "にがい", "しぶい"],
    answer: 3,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "辛い在食物语境读「からい」(辣),不是「つらい」(辛苦)", "action": "记搭配：辛い料理→辣的食物；辛い経験→痛苦的经历"},
  },
  {
    id: 2,
    level: "n2",
    type: "vocab_reading",
    question: "私の友人は刑事です。",
    options: ["けんじ", "かんじ", "けいじ", "かいじ"],
    answer: 1,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "刑事读「けいじ」(刑警),「けんじ」是検事(检察官)", "action": "区分：刑事(けいじ) vs 検事(けんじ)"},
  },
  {
    id: 3,
    level: "n2",
    type: "vocab_reading",
    question: "素晴らしい才能を発揮した。",
    options: ["ぜいのう", "ざいのう", "せいのう", "さいのう"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "才能读「さいのう」,财力「ざいりょく」,性能「せいのう」", "action": "背：才能(さいのう)=さい(才)+のう(能)"},
  },
  {
    id: 4,
    level: "n2",
    type: "vocab_reading",
    question: "夕方になって、ようやく風が収まった。",
    options: ["さだまった", "しずまった", "おさまった", "やすまった"],
    answer: 0,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "収まる(おさまる)=平息/收纳,静まる(しずまる)=安静", "action": "区分：収まる(おさまる,平息) vs 静まる(しずまる,安静)"},
  },
  {
    id: 5,
    level: "n2",
    type: "vocab_reading",
    question: "毎朝6時に起床して、少し運動をしている。",
    options: ["きしょう", "ぎしょう", "きしょ", "ぎしょ"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "起床读「きしょう」,不存在浊音读法", "action": "记：起(き)+床(しょう)=きしょう"},
  },
  {
    id: 6,
    level: "n2",
    type: "kanji",
    question: "この時期は風邪をひく人が増えるけいこうがある。",
    options: ["傾向", "頃向", "傾向", "頃向"],
    answer: 3,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "傾向(けいこう)=趋势,不存在「頃向」", "action": "倾向：傾(かたむ)く性質→傾向(けいこう)"},
  },
  {
    id: 7,
    level: "n2",
    type: "kanji",
    question: "このタオルはまだしめっている。",
    options: ["渡って", "温って", "汗って", "湿って"],
    answer: 0,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "湿る(しめる)=潮湿,渡る(わたる)=渡过", "action": "记：湿(しめ)=沾水→湿っている"},
  },
  {
    id: 8,
    level: "n2",
    type: "kanji",
    question: "もう少し力を入れてけずってください。",
    options: ["綾って", "削って", "揖って", "掘って"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "削る(けずる)=削/刮,掘る(ほる)=挖(向下)", "action": "区分：削る(けずる,削薄) vs 掘る(ほる,挖洞)"},
  },
  {
    id: 9,
    level: "n2",
    type: "kanji",
    question: "このしせつには駐車場はありません。",
    options: ["支接", "施接", "支設", "施設"],
    answer: 1,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "施設(しせつ)=设施,接是「接触」的接", "action": "记：施(し)+設(せつ)=施設(しせつ)"},
  },
  {
    id: 10,
    level: "n2",
    type: "kanji",
    question: "大勢の人がしさつに訪れた。",
    options: ["診察", "視祭", "視察", "診祭"],
    answer: 3,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "視察(しさつ)=视察,診察(しんさつ)=就诊", "action": "区分：視察(しさつ,视察) vs 診察(しんさつ,就诊)"},
  },
  {
    id: 11,
    level: "n2",
    type: "vocab_fill",
    question: "この魚は骨が多くて食べ（ ）。",
    options: ["づらい", "いたい", "おそい", "ぐるしい"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "食べづらい=难吃(因骨多),〜づらい=做起来困难", "action": "背：〜づらい(〜にくい的正式书面语)"},
  },
  {
    id: 12,
    level: "n2",
    type: "vocab_fill",
    question: "今回の事故は（ ）条件が重なって起きた。",
    options: ["損", "労", "危", "悪"],
    answer: 0,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "悪条件(あくじょうけん)=恶劣条件,不说危険条件", "action": "记：悪条件(あくじょうけん)→悪(わる)い条件"},
  },
  {
    id: 13,
    level: "n2",
    type: "vocab_fill",
    question: "教師たちの間で、新たな教育（ ）が注目されている。",
    options: ["則", "理", "論", "規"],
    answer: 3,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "教育論(きょういくろん)=教育理论,則/規是规则", "action": "记：教育論・経済論・言語論→論=theory学说"},
  },
  {
    id: 14,
    level: "n2",
    type: "vocab_context",
    question: "息子はみんなの前で、悪いことはもう絶対にしないと（ ）。",
    options: ["論じた", "命じた", "誓った", "迫った"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "誓う(ちかう)=发誓,「絶対にしない」接发誓", "action": "区分：誓う(发誓) vs 論じる(论述) vs 命じる(命令)"},
  },
  {
    id: 15,
    level: "n2",
    type: "vocab_context",
    question: "工事のため、（ ）電気が止まることがあります。",
    options: ["簡潔に", "一時的に", "手軽に", "不完全に"],
    answer: 1,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "一時的(いちじてき)=暂时的,工事停电是临时", "action": "背：一時的(いちじてき)=temporary"},
  },
  {
    id: 16,
    level: "n2",
    type: "vocab_context",
    question: "あの人物が今回の事件に（ ）していたのは間違いない。",
    options: ["参列", "加入", "登場", "関与"],
    answer: 3,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "関与(かんよ)=参与(负面),事件に関与=涉案", "action": "区分：関与(涉案) vs 参列(出席仪式)"},
  },
  {
    id: 17,
    level: "n2",
    type: "vocab_context",
    question: "油で汚れたフライパンは（ ）してとても洗いにくいです。",
    options: ["べたべた", "かさかさ", "じめじめ", "ちくちく"],
    answer: 0,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "べたべた=黏糊糊(油),かさかさ=干,じめじめ=潮,ちくちく=刺痛", "action": "拟声词：べたべた(黏)・かさかさ(干)"},
  },
  {
    id: 18,
    level: "n2",
    type: "vocab_context",
    question: "サッカーで手を使うのは禁止されていて、もし使ったら（ ）になる。",
    options: ["反則", "違法", "非常識", "不都合"],
    answer: 0,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "反則(はんそく)=犯规(比赛规则),違法是法律", "action": "区分：反則(比赛) vs 違法(法律)"},
  },
  {
    id: 19,
    level: "n2",
    type: "vocab_context",
    question: "虫が飛んできたので、手に持っていた帽子を振って遠くに（ ）。",
    options: ["連れ出した", "締め出した", "取り払った", "追い払った"],
    answer: 3,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "追い払う(おいはらう)=赶走,虫を帽子で追い払う", "action": "记：追い払う=追って払う→赶走"},
  },
  {
    id: 20,
    level: "n2",
    type: "vocab_context",
    question: "社会の変化に合わせて、働き方や休日の過ごし方など人々が選ぶ生活の（ ）も変わってきた。",
    options: ["ポーズ", "スタイル", "ブランド", "シリーズ"],
    answer: 1,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "生活スタイル=生活方式", "action": "记：生活スタイル=lifestyle"},
  },
  {
    id: 21,
    level: "n2",
    type: "meaning",
    question: "昨夜、家の近くで妙な事件が起こった。",
    stem_word: "妙な",
    options: ["恐ろしい", "不思議な", "悲しい", "重大な"],
    answer: 1,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "妙(みょう)=奇怪/不可思议,近义「不思議」", "action": "记：妙な=不思議な=strange/odd"},
  },
  {
    id: 22,
    level: "n2",
    type: "meaning",
    question: "鈴木さんは相当迷っているらしい。",
    stem_word: "相当",
    options: ["いろいろ", "まだ", "やっぱり", "かなり"],
    answer: 3,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "相当(そうとう)=相当地/颇,近义「かなり」", "action": "背：相当=かなり=quite/considerably"},
  },
  {
    id: 23,
    level: "n2",
    type: "meaning",
    question: "教室がやかましくて、勉強に集中できない。",
    stem_word: "やかましくて",
    options: ["うるさくて", "汚くて", "暑くて", "暗くて"],
    answer: 0,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "やかましい=吵闹,近义「うるさい」", "action": "记：やかましい≈うるさい(但更正式)"},
  },
  {
    id: 24,
    level: "n2",
    type: "meaning",
    question: "中山さんは帰省しています。",
    stem_word: "帰省",
    options: ["出張から戻って", "部屋に戻って", "ふるさとに戻って", "休みから戻って"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "帰省(きせい)=回老家探亲", "action": "记：帰省→帰る+省(みる)→回老家看看"},
  },
  {
    id: 25,
    level: "n2",
    type: "meaning",
    question: "林さんはいきなり振り向いた。",
    stem_word: "いきなり",
    options: ["やっと", "一度", "突然", "ゆっくり"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "いきなり=突然(without warning)", "action": "背：いきなり=突然(suddenly)"},
  },
  {
    id: 26,
    level: "n2",
    type: "usage",
    question: "潰す",
    options: ["ガラスのコップを落として、潰してしまった。", "空き缶は潰してからごみ箱に入れてください。", "洗濯物が乾いたので、きれいに潰してたんすにしまった。", "いらなくなった書類をびりびりと細かく潰して捨てた。"],
    answer: 1,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "潰す(つぶす)=压扁(立体变扁平),空罐压扁是正解", "action": "记：潰す是把东西压扁,玻璃杯摔碎是割れる"},
  },
  {
    id: 27,
    level: "n2",
    type: "usage",
    question: "粗末",
    options: ["昔の学校給食は、おかずの種類も少なく今と比べると粗末なものだった。", "言葉遣いが粗末だったので、友達を怒らせてしまった。", "風邪をひいてしまい、声が粗末で上手に歌えない。", "お金がないので、友人がくれた古くて機能が粗末なパソコンを使っている。"],
    answer: 0,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "粗末(そまつ)=简陋,只用于物品/食物不用于语言", "action": "言葉遣いが粗い(粗い不是粗末),声がかすれている(嘶哑)"},
  },
  {
    id: 28,
    level: "n2",
    type: "usage",
    question: "熱中",
    options: ["ごみ処理の問題に関して、市民から担当者に批判が熱中した。", "学生のときは野球に熱中していて、毎日遅くまで練習していた。", "うちの娘はこの服に熱中していて、毎月こればかり着たがります。", "オリンピックの期間中、世界の関心が開催地に熱中している。"],
    answer: 1,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "熱中(ねっちゅう)=热衷于活动/爱好,不用于物", "action": "用法：活動に熱中する,物にこだわる"},
  },
  {
    id: 29,
    level: "n2",
    type: "usage",
    question: "和やか",
    options: ["火事や地震のときは、慌てずに和やかな行動を取ることが重要だ。", "この地方は一年中気候が和やかなので暮らしやすい。", "この店のスープは和やかな味で飲むとほっとする。", "代表者同士の話し合いは、和やかな雰囲気で行われた。"],
    answer: 3,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "和やか(なごやか)=融洽和睦,只用于气氛/会议", "action": "记：和やかな雰囲気=融洽气氛"},
  },
  {
    id: 30,
    level: "n2",
    type: "usage",
    question: "愛着",
    options: ["いろいろな靴を履いてみたが、どれも愛着がなかったので買わなかった。", "スーパーで、地元の人が愛着を入れて育てた野菜を買った。", "この机はもう使っていないのだが、愛着があってなかなか捨てられない。", "弟は教師になるという夢に愛着を持ち、教育学部に進学した。"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "愛着(あいちゃく)=对旧物/人的依恋不舍,不用在梦想", "action": "区分：愛着(依恋旧物) vs 執着(执着)"},
  },
  {
    id: 31,
    level: "n2",
    type: "grammar",
    question: "市は、市民ホールを建設する（ ）周辺の住民に対して説明会を行う予定だ。",
    options: ["とすると", "にあたって", "ものなら", "わりには"],
    answer: 1,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "〜にあたって=在...之际(建设前开说明会)", "action": "记：〜にあたって=〜に際して(在...之际)"},
  },
  {
    id: 32,
    level: "n2",
    type: "grammar",
    question: "彼女は、まだ小学生（ ）すでに数々の国際的なピアノコンクールで優勝している。",
    options: ["こそ", "すら", "ながらも", "どころか"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "〜ながらも=虽然...却(小学生ながらも優勝→逆接)", "action": "记：ながらも=逆接(虽然...但是)"},
  },
  {
    id: 33,
    level: "n2",
    type: "grammar",
    question: "仕事ができると言われる人は、そうでない人と比べて（ ）何が違うのだろうか。",
    options: ["いったい", "せっかく", "まさか", "もしかすると"],
    answer: 0,
    source: "2025-07",
    error_analysis: {"category": "A", "clue": "いったい(一体)=究竟,疑问句中表强烈追问", "action": "背：いったい(一体)=究竟(exactly)"},
  },
  {
    id: 34,
    level: "n2",
    type: "grammar",
    question: "（旅館で）旅館の人「いらっしゃいませ。本日は森川旅館に（ ）いただき、ありがとうございます。」",
    options: ["伺いまして", "お越しになり", "参りまして", "おいでくださり"],
    answer: 1,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "おいでくださる=「来る」最高尊敬,旅馆对客人", "action": "敬语：参る(谦逊)→お越しになる(尊敬)→おいでくださる(最高)"},
  },
  {
    id: 35,
    level: "n2",
    type: "grammar",
    question: "父は、健康のことを考えてなるべく（ ）会社から家まで1時間かけて歩いて帰ってくることもある。",
    options: ["歩こうとしそうで", "歩こうとすることで", "歩くようにしているらしく", "歩くようにしていたら"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "〜ようにしている(努力做到)+らしく(好像)", "action": "记：〜ようにしている(努力去做)+なるべく(尽量)"},
  },
  {
    id: 36,
    level: "n2",
    type: "grammar",
    question: "図書館で本を借りたのだが、最後まで（ ）返却期限が来そうだ。",
    options: ["読み終わるより", "読み終わらないうちに", "読んでしまうまで", "読んでしまわなければ"],
    answer: 1,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "〜ないうちに=趁还没...,没读完但期限到了", "action": "用法：〜ないうちに(趁还没) vs 〜うちに(趁...时)"},
  },
  {
    id: 37,
    level: "n2",
    type: "grammar",
    question: "最近成績が伸びないので、このままの勉強方法（ ）先生に相談してみた。",
    options: ["でいいことを", "ならいいことを", "でいいのかどうか", "ならいいのかどうか"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "〜でいいのかどうか=这样是否OK,で(手段)+いいのか", "action": "记：〜で(手段/状态)いいのかどうか"},
  },
  {
    id: 38,
    level: "n2",
    type: "grammar",
    question: "環境問題への意識が世界的に高まってきており、メーカー間の電気自動車の開発競争は激しくなる（ ）。",
    options: ["一方だ", "次第だ", "ほどだ", "べきだ"],
    answer: 0,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "〜一方だ=越来越(单向持续变化)", "action": "区分：一方だ(持续变化) vs 次第だ(取决于)"},
  },
  {
    id: 39,
    level: "n2",
    type: "grammar",
    question: "週末、山に登った。とても暑い日だったが、頂上の近くは気温が低くて寒い（ ）。",
    options: ["とよかった", "に違いなかった", "かのようだった", "くらいだった"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "〜かのようだった=仿佛...一样", "action": "记：〜かのようだ=as if(まるで〜ようだ正式版)"},
  },
  {
    id: 40,
    level: "n2",
    type: "grammar",
    question: "満員電車に乗るのは嫌だが、ほかに手段がないので（ ）。",
    options: ["乗るものではない", "乗りようがない", "乗らないわけにはいかない", "乗らなくてもかまわない"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "〜ないわけにはいかない=不得不", "action": "记：〜ざるを得ない≈〜ないわけにはいかない(不得不)"},
  },
  {
    id: 41,
    level: "n2",
    type: "grammar",
    question: "（テレビ番組で）司会「薬はどうして水以外の飲み物で飲んではいけないんでしょうか。」医者「それは、お茶やジュースで飲むと薬の効きめに影響が出る（ ）。」",
    options: ["ことがあるためです", "ことにするためです", "ことがあるはずです", "ことにするはずです"],
    answer: 0,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "〜ことがある=有时会(不是每次都影响但有时会)→原因", "action": "区分：ことがある(有时) vs ことにしている(习惯/规定)"},
  },
  {
    id: 42,
    level: "n2",
    type: "grammar",
    question: "私は猫アレルギーで、猫に触ると体がかゆくなってしまうのだが、猫は好きなので見るとつい（ ）。",
    options: ["触ってみたがっている", "触ってみたくなってしまう", "触ってみてほしがっている", "触ってみてほしくなってしまう"],
    answer: 1,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "〜たくなってしまう=忍不住想做", "action": "构造：たい(想)+なる(变成)+てしまう(忍不住)=たくなってしまう"},
  },
  {
    id: 43,
    level: "n2",
    type: "grammar_fill",
    question: "このパン屋では、原料の【★】一つ一つ丁寧にパンを作っているそうだ。",
    options: ["もちろん", "水にまで", "こだわって", "小麦粉は"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "★=こだわって,原文：小麦粉はもちろん水にまでこだわって", "action": "排序：もちろん→水にまで→こだわって(连水都讲究)"},
  },
  {
    id: 44,
    level: "n2",
    type: "grammar_fill",
    question: "昨日は、梅雨の【★】久しぶりに洗濯物を外に干すことができた。",
    options: ["この", "珍しく", "いい天気で", "時期にしては"],
    answer: 3,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "★=この,原文：この時期にしては珍しくいい天気で", "action": "排序：この→時期にしては→珍しく→いい天気で"},
  },
  {
    id: 45,
    level: "n2",
    type: "grammar_fill",
    question: "今回のセミナーの開催日が人の【★】参加者が集まったのは大成功といえる。",
    options: ["200名もの", "集まりにくい", "平日だった", "ことを考えると"],
    answer: 1,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "★=集まりにくい,原文：集まりにくい平日だったことを考えると", "action": "排序：集まりにくい→平日だった→ことを考えると"},
  },
  {
    id: 46,
    level: "n2",
    type: "grammar_fill",
    question: "人には【★】気づくのは難しい。",
    options: ["自分でそれに", "良さがあるというが", "その人にしかない", "誰にでも"],
    answer: 0,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "★=自分でそれに,原文：自分でそれに気づくのは難しい", "action": "排序：その人にしかない→良さがあるというが→自分でそれに→気づく"},
  },
  {
    id: 47,
    level: "n2",
    type: "grammar_fill",
    question: "昨夜、目覚まし時計をセットするのを忘れてしまい、今朝は寝坊してしまった。それで【★】からだ。",
    options: ["のは", "たまたまかかってきた", "電話に起こされた", "遅刻をせずに済んだ"],
    answer: 1,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "★=のは,排序：たまたまかかってきた電話に起こされたのは遅刻をせずに済んだからだ", "action": "排序：〜のは〜からだ(正是因为...才没迟到)"},
  },
  {
    id: 48,
    level: "n2",
    type: "grammar_fill",
    question: "先日、友人と市内の新しい美術館に行った。非常に楽しみに（ 48 ）、想像していたよりはるかに面白かった。",
    options: ["して以来", "してからというもの", "していたところ", "していたものの"],
    answer: 1,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "〜していたものの=虽然很期待(但...),前后逆接", "action": "记：〜ものの(虽然...但是,书面逆接)"},
  },
  {
    id: 49,
    level: "n2",
    type: "grammar_fill",
    question: "（同文）展示物は、どれも細部まで丁寧に作られており、何時間でも（ 49 ）ほど魅力的だった。",
    options: ["見飽きない", "見飽きる", "見飽きかねない", "見飽きようがない"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "見飽きない(看不腻)+ほど=看不腻的程度", "action": "构造：ます形+飽きる=腻,見飽きない=不腻"},
  },
  {
    id: 50,
    level: "n2",
    type: "grammar_fill",
    question: "（同文）特に、地元の芸術家による作品のコーナーは印象的で、思わず何度も足を（ 50 ）。",
    options: ["止めさせるのを忘れた", "止めさせるほどだった", "止められないのを忘れた", "止められないほどだった"],
    answer: 3,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "足を止められないほどだった=让人忍不住驻足", "action": "记：足を止める=停下脚步,〜ほどだった=到...程度"},
  },
  {
    id: 51,
    level: "n2",
    type: "grammar_fill",
    question: "（同文）帰り道、友人と「ああいう展覧会は、また（ 51 ）ね」と話しながら帰った。",
    options: ["行きたい", "行くものか", "行こう", "行くことか"],
    answer: 0,
    source: "2025-07",
    error_analysis: {"category": "B", "clue": "また行きたいね=还想再去(表示愿望)", "action": "记：また行きたい(还想再去)"},
  },
  {
    id: 52,
    level: "n2",
    type: "reading_short",
    question: "(1) この文章で筆者が最も伝えたいことは何か。",
    passage: "散歩の魅力は、目的がないことだ。ただ歩くこと、風を感じること、季節の変化に気づくこと。何かを「しなければ」という気持ちで歩くのではなく、ただ歩くことに没頭することで、心が解放される。何もしないことへの罪悪感を捨て、散歩そのものを目的にすることで、私たちは本当の意味でのリラックスを得られるのではないか。",
    options: ["散歩をするときは目的地を決めずに歩くほうが心が解放される。", "散歩を楽しむためには、季節の変化を感じることが大切だ。", "散歩をすることで、何もしないことへの罪悪感が消える。", "散歩の目的はただリラックスすることだけではなく、運動にもなることだ。"],
    answer: 0,
    source: "2025-07",
    error_analysis: {"category": "C", "clue": "筆者は「目的がないこと=解放」为核心,最后「散歩そのものを目的に」", "action": "读解技巧：找「最も伝えたい」=首尾结论句"},
  },
  {
    id: 53,
    level: "n2",
    type: "reading_short",
    question: "(2) このメールで問い合わせていることは何か。",
    passage: "水石食品 商品開発部 田中由夏 様\n\n昨日は「水石りんごジャム」のサンプルをお送りいただき、ありがとうございました。\n\n本日、試食をし、予定どおり来月から朝食で提供することにいたしました。\n\nまた、お客様から名産のりんごを使ったお土産がないかたびたびご質問を受けますので、このジャムを売店でも販売したいと考えております。同じ時期に販売を開始したいと思っておりますが、ご対応いただけるでしょうか。\n\nご検討いただきたく、どうぞよろしくお願いいたします。\n\n水石温泉ホテル 営業部 島本洋太",
    options: ["来月から「水石りんごジャム」をホテルの朝食で提供できるか。", "来月から販売予定の「水石りんごジャム」は、名産のりんごを使っているか。", "来月までに名産のりんごを使った新しい土産品が作れるか。", "売店で販売するための「水石りんごジャム」を、来月から納品できるか。"],
    answer: 3,
    source: "2025-07",
    error_analysis: {"category": "C", "clue": "关键「このジャムを売店でも販売したい」「ご対応いただけるでしょうか」", "action": "技巧：メールの問い合わせ＝最後の質問句"},
  },
  {
    id: 54,
    level: "n2",
    type: "reading_short",
    question: "(3) ラジオについて、筆者はどのように考えているか。",
    passage: "ラジオというのはながら聴きができるところが好きだった。何か他のことをしながら聴く。いい音楽や話があると、それが突然まるでボリュームが上がったように大きく聞こえ、そこから頭の中に空想の世界が浮かびだす。ラジオは余白のあるメディアだ。音しかそこには存在しないわけで、そこから先は聞き手である自分たちの手に委ねられる。まるで本で読む小説のように。与えられる情報が少ないほど、ある意味、自由度が高い。",
    options: ["他のことをしながら聞けるので、時間が有効に使える。", "いい音楽や話が聞けて、自由が感じられる。", "音以外の情報がなく、自由に空想が広がりやすい。", "目からの情報がなく、小説より自由に空想ができる。"],
    answer: 2,
    source: "2025-07",
    error_analysis: {"category": "C", "clue": "核心「余白のあるメディア」「音しかない→自由度が高い」", "action": "注意：「余白」=空白→暗示想象力空间"},
  },
  {
    id: 55,
    level: "n2",
    type: "reading_short",
    question: "(4) ガスの使用量と料金の確認について、今後どのように変わるか。",
    passage: "いつも坂元ガスをご利用いただき、ありがとうございます。\n\nこれまで月々のガスの使用量と料金は、紙の通知書でお伝えしていましたが、資源節約のため8月末で廃止いたします。9月以降、使用量と料金の確認は、ウェブ会員サービス「サカモトガスネット」をご利用ください。引き続き通知書をご希望のお客様には郵送でお届けいたしますが、手数料180円/月をご負担いただきます。",
    options: ["9月からはガスの使用量と料金はウェブで確認するのが基本になり、引き続き紙の通知を希望する人は手数料が必要になる。", "8月末までは紙の通知書が届くが、その後は連絡がないので、各自でウェブに登録しなければならなくなる。", "9月からはウェブ会員サービスでの確認のみになり、紙の通知書は完全に廃止される。", "紙の通知書は有料化されるが、8月末までは手数料無料で受け取ることができる。"],
    answer: 3,
    source: "2025-07",
    error_analysis: {"category": "C", "clue": "「8月末で廃止→9月以降ウェブ」「通知書希望者は有料」", "action": "读解：数字(8月末/9月/180円)+转折(が)是关键"},
  },
  {
    id: 56,
    level: "n2",
    type: "reading_short",
    question: "(5) 会社について、筆者はどのように述べているか。",
    passage: "仕事というものは、自分の専門分野のことだけ考えればよいのではなく、専門を超えてどんな影響を与え合うか考え調整しながらやるべきものである。自部門に余裕があれば、忙しい他部門を手伝ってあげるべきだが、誰もそういう具合には考えない。そして、いつのまにか自分の城を築き、守りに入る。これでは「会社」ではない。会社は、そこで働く普通の人たちの力が、みんなで働くことによって何倍にも大きくなり、個人では成しえないような偉大なことを行う場所である。",
    options: ["各部門の仕事量に差があると、会社は発展していかない。", "部門を分けないほうが、会社は大きな成果を上げられる。", "部門内で助け合って仕事をしていれば、社内の雰囲気もよくなる。", "部門同士が互いのことを考えて仕事をしなければ、会社とはいえない。"],
    answer: 3,
    source: "2025-07",
    error_analysis: {"category": "C", "clue": "最後の筆者主張=「自分の城を築く→これでは会社ではない」→否定句的反面为正解", "action": "读解技巧：找否定句(ではない)→反面为正解"},
  },
];