const QUIZ_DATA_HIGH = [
  {
    id:1,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「影響」",
    options:["じんこう", "えいきょう", "りよう", "さんぎょう"],
    answer: 1,
    explanation:"「影響」は「えいきょう」と読みます。意味：影响",
    source:"N2真题 2020",
  },
  {
    id:2,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>最新の（  ）を手に入れた。",
    options:["だんだん", "情報", "初歩", "認識"],
    answer: 1,
    explanation:"「情報」：信息",
    source:"N2真题 2019",
  },
  {
    id:3,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「場合」",
    options:["すう", "ふやす", "ばあい", "けす"],
    answer: 2,
    explanation:"「場合」は「ばあい」と読みます。意味：场合；情况",
    source:"N2真题 2018",
  },
  {
    id:4,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>雨にもかかわらず、試合は行われた。",
    options:["〜にもかかわらず", "〜というより", "〜に関わらず", "〜ものだから"],
    answer: 0,
    explanation:"「〜にもかかわらず」：尽管〜；虽然〜却",
    source:"N2真题 2022",
  },
  {
    id:5,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「問題」",
    options:["ふれる", "せつび", "もんだい", "まもる"],
    answer: 2,
    explanation:"「問題」は「もんだい」と読みます。意味：问题",
    source:"N2真题 2012",
  },
  {
    id:6,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「環境」",
    options:["しゅとく", "めいだい", "しんよう", "かんきょう"],
    answer: 3,
    explanation:"「環境」は「かんきょう」と読みます。意味：环境",
    source:"N2真题 2019",
  },
  {
    id:7,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>国際（  ）が緊張している。",
    options:["論理", "自発", "参考", "関係"],
    answer: 3,
    explanation:"「関係」：关系",
    source:"N2真题 2023",
  },
  {
    id:8,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「経済」",
    options:["けいざい", "きおく", "さんだん", "きゅうぞう"],
    answer: 0,
    explanation:"「経済」は「けいざい」と読みます。意味：经济",
    source:"N2真题 2022",
  },
  {
    id:9,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「経験」",
    options:["さからう", "けいけん", "かくだい", "かんり"],
    answer: 1,
    explanation:"「経験」は「けいけん」と読みます。意味：经验；经历",
    source:"N2真题 2012",
  },
  {
    id:10,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「手続き」",
    options:["しっこう", "きせい", "てつづき", "だんだん"],
    answer: 2,
    explanation:"「手続き」は「てつづき」と読みます。意味：手续",
    source:"N2真题 2017",
  },
  {
    id:11,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「参加」",
    options:["さんか", "ちゅうおう", "きかん", "ぎゃくてん"],
    answer: 0,
    explanation:"「参加」は「さんか」と読みます。意味：参加",
    source:"N2真题 2014",
  },
  {
    id:12,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「可能」",
    options:["たいりょう", "かのう", "めいだい", "きょうきゅう"],
    answer: 1,
    explanation:"「可能」は「かのう」と読みます。意味：可能",
    source:"N2真题 2014",
  },
  {
    id:13,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）を収集する。",
    options:["情報", "技術", "可能性", "届ける"],
    answer: 0,
    explanation:"「情報」：信息",
    source:"N2真题 2018",
  },
  {
    id:14,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「社会」",
    options:["かてい", "しゃかい", "ぶつり", "のぼる"],
    answer: 1,
    explanation:"「社会」は「しゃかい」と読みます。意味：社会",
    source:"N2真题 2019",
  },
  {
    id:15,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>先生の質問に対して、学生が答えた。",
    options:["〜に関わらず", "〜を通じて（通して）", "〜に対して", "〜にすぎない"],
    answer: 2,
    explanation:"「〜に対して」：对于〜；针对〜",
    source:"N2真题 2020",
  },
  {
    id:16,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「重要」",
    options:["さがす", "じゅうよう", "はじめる", "しかたがない"],
    answer: 1,
    explanation:"「重要」は「じゅうよう」と読みます。意味：重要",
    source:"N2真题 2016",
  },
  {
    id:17,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>正しい（  ）を入手する。",
    options:["曲がる", "努力", "情報", "連絡"],
    answer: 2,
    explanation:"「情報」：信息",
    source:"N2真题 2023",
  },
  {
    id:18,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「安全」",
    options:["たのしみ", "ろんり", "あんぜん", "としょかん"],
    answer: 2,
    explanation:"「安全」は「あんぜん」と読みます。意味：安全",
    source:"N2真题 2019",
  },
  {
    id:19,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>スポーツにおいて、チームワークが重要だ。",
    options:["〜かねる", "〜ことなく", "〜にしたがって", "〜において"],
    answer: 3,
    explanation:"「〜において」：在〜（方面/场合）",
    source:"N2真题 2019",
  },
  {
    id:20,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>この（  ）を逃さないで。",
    options:["商品", "任務", "機会", "拳固"],
    answer: 2,
    explanation:"「機会」：机会",
    source:"N2真题 2012",
  },
  {
    id:21,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「技術」",
    options:["しょり", "ぐうぜん", "ぎじゅつ", "いはん"],
    answer: 2,
    explanation:"「技術」は「ぎじゅつ」と読みます。意味：技术",
    source:"N2真题 2021",
  },
  {
    id:22,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「効果」",
    options:["いりょう", "さえ", "だんだん", "こうか"],
    answer: 3,
    explanation:"「効果」は「こうか」と読みます。意味：效果",
    source:"N2真题 2011",
  },
  {
    id:23,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>環境問題に関して、意見を述べた。",
    options:["〜に関して", "〜というのは", "〜わけだ", "〜さえ〜ば"],
    answer: 0,
    explanation:"「〜に関して」：关于〜；有关〜",
    source:"N2真题 2011",
  },
  {
    id:24,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>来年（  ）する予定だ。",
    options:["新鮮", "評価", "結婚", "抽象"],
    answer: 2,
    explanation:"「結婚」：结婚",
    source:"N2真题 2013",
  },
  {
    id:25,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>この（ 　）はとても大切だ。",
    options:["電源", "取得", "勧告", "続ける"],
    answer: 3,
    explanation:"「続ける」：继续",
    source:"N2真题 2020",
  },
  {
    id:26,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>旅行を（  ）にしている。",
    options:["図書館", "分析", "楽しみ", "観点"],
    answer: 2,
    explanation:"「楽しみ」：乐趣；期待",
    source:"N2真题 2010",
  },
  {
    id:27,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>会社の（  ）を立て直した。",
    options:["取得", "研究", "機能", "経営"],
    answer: 3,
    explanation:"「経営」：经营",
    source:"N2真题 2012",
  },
  {
    id:28,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>この（  ）はよく売れている。",
    options:["好况", "初歩", "商品", "補佐"],
    answer: 2,
    explanation:"「商品」：商品",
    source:"N2真题 2010",
  },
  {
    id:29,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>ボランティア（  ）に参加する。",
    options:["辛い", "疾病", "活動", "経営"],
    answer: 2,
    explanation:"「活動」：活动",
    source:"N2真题 2017",
  },
  {
    id:30,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>天気予報によると、明日は晴れるそうだ。",
    options:["〜によると", "〜をはじめ（として）", "〜にあたって", "〜に加えて"],
    answer: 0,
    explanation:"「〜によると」：据〜说；根据〜",
    source:"N2真题 2014",
  },
  {
    id:31,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「期待」",
    options:["ほさ", "だんだん", "はいたつ", "きたい"],
    answer: 3,
    explanation:"「期待」は「きたい」と読みます。意味：期待",
    source:"N2真题 2012",
  },
  {
    id:32,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>彼の仕事は高く（  ）されている。",
    options:["助ける", "文化", "趣味", "評価"],
    answer: 3,
    explanation:"「評価」：评价；评估",
    source:"N2真题 2010",
  },
  {
    id:33,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「努力」",
    options:["しつもん", "どりょく", "かわく", "こえる"],
    answer: 1,
    explanation:"「努力」は「どりょく」と読みます。意味：努力",
    source:"N2真题 2023",
  },
  {
    id:34,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）が変わった。",
    options:["違う", "状況", "現実", "都会"],
    answer: 1,
    explanation:"「状況」：状况；情况",
    source:"N2真题 2019",
  },
  {
    id:35,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>顔が赤いことから、恥ずかしいとわかる。",
    options:["〜ことから", "〜てたまらない", "〜にすぎない", "〜ではないか"],
    answer: 0,
    explanation:"「〜ことから」：由于〜；从〜可以看出",
    source:"N2真题 2020",
  },
  {
    id:36,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「絶対」",
    options:["はっそう", "はいけん", "じょうしき", "ぜったい"],
    answer: 3,
    explanation:"「絶対」は「ぜったい」と読みます。意味：绝对",
    source:"N2真题 2017",
  },
  {
    id:37,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>休むことなく、働き続けた。",
    options:["〜一方で", "〜ことなく", "〜を契機に", "〜わけだ"],
    answer: 1,
    explanation:"「〜ことなく」：不〜地；没有〜就",
    source:"N2真题 2012",
  },
  {
    id:38,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>彼は英語だけでなく、中国語も話せる。",
    options:["〜とともに", "〜によると", "〜ほど", "〜だけでなく"],
    answer: 3,
    explanation:"「〜だけでなく」：不仅〜，而且〜",
    source:"N2真题 2017",
  },
  {
    id:39,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「文化」",
    options:["としょかん", "むく", "ゆうこう", "ぶんか"],
    answer: 3,
    explanation:"「文化」は「ぶんか」と読みます。意味：文化",
    source:"N2真题 2020",
  },
  {
    id:40,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>来月ヨーロッパへ（  ）する。",
    options:["旅行", "人々", "温度", "社会"],
    answer: 0,
    explanation:"「旅行」：旅行",
    source:"N2真题 2014",
  },
  {
    id:41,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>嫌いなわけではないが、得意ではない。",
    options:["〜ようとする", "〜わけではない", "〜に沿って", "〜かねる"],
    answer: 1,
    explanation:"「〜わけではない」：并非〜；不是说〜",
    source:"N2真题 2014",
  },
  {
    id:42,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「理解」",
    options:["りかい", "きめる", "こえる", "かかえる"],
    answer: 0,
    explanation:"「理解」は「りかい」と読みます。意味：理解",
    source:"N2真题 2010",
  },
  {
    id:43,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「経済」",
    options:["こころみる", "しゃかい", "しゅだん", "けいざい"],
    answer: 3,
    explanation:"「経済」は「けいざい」と読みます。意味：经济",
    source:"N2真题 2018",
  },
  {
    id:44,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「確認」",
    options:["しはらい", "かくにん", "しはらう", "こうじょう"],
    answer: 1,
    explanation:"「確認」は「かくにん」と読みます。意味：确认",
    source:"N2真题 2012",
  },
  {
    id:45,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>約束があるから、行かないわけにはいかない。",
    options:["〜上で", "〜さえ〜ば", "〜わけにはいかない", "〜を契機に"],
    answer: 2,
    explanation:"「〜わけにはいかない」：不能〜；没办法〜（情理上不允许）",
    source:"N2真题 2015",
  },
  {
    id:46,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>物価が上がる一方だ。",
    options:["〜一方だ", "〜からといって", "〜てたまらない", "〜を契機に"],
    answer: 0,
    explanation:"「〜一方だ」：越来越〜；持续〜",
    source:"N2真题 2022",
  },
  {
    id:47,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>彼女は仕事をしている一方で、子育てもしている。",
    options:["〜に対して", "〜一方で", "〜さえ〜ば", "〜に応じて"],
    answer: 1,
    explanation:"「〜一方で」：一方面〜，另一方面〜",
    source:"N2真题 2022",
  },
  {
    id:48,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>雨のせいで、試合が中止になった。",
    options:["〜ものの", "〜さえ〜ば", "〜せいで", "〜に対し"],
    answer: 2,
    explanation:"「〜せいで」：都是因为〜（负面原因）",
    source:"N2真题 2022",
  },
  {
    id:49,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>先生のおかげで、試験に合格した。",
    options:["〜というより", "〜ほど", "〜おかげで", "〜に際して"],
    answer: 2,
    explanation:"「〜おかげで」：多亏〜（正面原因）",
    source:"N2真题 2023",
  },
  {
    id:50,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「説明」",
    options:["せつめい", "ほこり", "ろんぶん", "とうし"],
    answer: 0,
    explanation:"「説明」は「せつめい」と読みます。意味：说明",
    source:"N2真题 2020",
  },
  {
    id:51,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「経済」",
    options:["きめる", "いんさつ", "けいざい", "ほうこく"],
    answer: 2,
    explanation:"「経済」は「けいざい」と読みます。意味：经济",
    source:"N2真题 2010",
  },
  {
    id:52,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>あの車は高いに違いない。",
    options:["〜上で", "〜とともに", "〜から見ると", "〜に違いない"],
    answer: 3,
    explanation:"「〜に違いない」：一定是〜；肯定〜",
    source:"N2真题 2015",
  },
  {
    id:53,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「経済」",
    options:["けいざい", "のに", "こみゅにけーしょん", "せいぞう"],
    answer: 0,
    explanation:"「経済」は「けいざい」と読みます。意味：经济",
    source:"N2真题 2014",
  },
  {
    id:54,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>経済の発展にしたがって、生活が豊かになった。",
    options:["〜に反して", "〜とともに", "〜から見ると", "〜にしたがって"],
    answer: 3,
    explanation:"「〜にしたがって」：随着〜；按照〜",
    source:"N2真题 2020",
  },
  {
    id:55,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「意見」",
    options:["えんちょう", "いけん", "しゅっぱん", "しゅよう"],
    answer: 1,
    explanation:"「意見」は「いけん」と読みます。意味：意见",
    source:"N2真题 2018",
  },
  {
    id:56,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>まだ（  ）はある。",
    options:["実施", "可能性", "原因", "範囲"],
    answer: 1,
    explanation:"「可能性」：可能性",
    source:"N2真题 2016",
  },
  {
    id:57,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「期待」",
    options:["じしゅ", "きたい", "きこう", "しゅとく"],
    answer: 1,
    explanation:"「期待」は「きたい」と読みます。意味：期待",
    source:"N2真题 2014",
  },
  {
    id:58,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>高齢化に伴って、医療費が増加している。",
    options:["〜ものだから", "〜にしたがって", "〜をはじめ（として）", "〜に伴って"],
    answer: 3,
    explanation:"「〜に伴って」：随着〜；伴随〜",
    source:"N2真题 2022",
  },
  {
    id:59,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>試験に合格したものの、自信が持てない。",
    options:["〜を通じて（通して）", "〜に関して", "〜ものの", "〜一方で"],
    answer: 2,
    explanation:"「〜ものの」：虽然〜但是（转折）",
    source:"N2真题 2011",
  },
  {
    id:60,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「原因」",
    options:["ろうどく", "げんいん", "もくひょう", "さからう"],
    answer: 1,
    explanation:"「原因」は「げんいん」と読みます。意味：原因",
    source:"N2真题 2012",
  },
  {
    id:61,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「危険」",
    options:["さんか", "ぐあい", "きけん", "よういん"],
    answer: 2,
    explanation:"「危険」は「きけん」と読みます。意味：危险",
    source:"N2真题 2017",
  },
  {
    id:62,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>家族と（  ）に暮らしたい。",
    options:["幸せ", "展覧会", "実践", "社会学"],
    answer: 0,
    explanation:"「幸せ」：幸福",
    source:"N2真题 2010",
  },
  {
    id:63,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>毎朝30分走ることにしている。",
    options:["〜ことにしている", "〜として", "〜というより", "〜にしたがって"],
    answer: 0,
    explanation:"「〜ことにしている」：（习惯上）坚持〜",
    source:"N2真题 2022",
  },
  {
    id:64,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>ドアを開けようとしたが、開かなかった。",
    options:["〜ようとする", "〜にすぎない", "〜にあたって", "〜にもかかわらず"],
    answer: 0,
    explanation:"「〜ようとする」：试图〜；想要〜（努力尝试）",
    source:"N2真题 2012",
  },
  {
    id:65,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>こんなにきれいじゃないか。",
    options:["〜一方で", "〜ではないか", "〜ことなく", "〜にほかならない"],
    answer: 1,
    explanation:"「〜ではないか」：不是〜吗（反问确认）",
    source:"N2真题 2022",
  },
  {
    id:66,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「調査」",
    options:["しえん", "こうまい", "きぎょう", "ちょうさ"],
    answer: 3,
    explanation:"「調査」は「ちょうさ」と読みます。意味：调查",
    source:"N2真题 2021",
  },
  {
    id:67,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>それは（  ）の結果だ。",
    options:["当然", "熱意", "権利", "訓練"],
    answer: 0,
    explanation:"「当然」：当然",
    source:"N2真题 2016",
  },
  {
    id:68,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「卒業」",
    options:["かいほう", "そつぎょう", "しんか", "しょくじ"],
    answer: 1,
    explanation:"「卒業」は「そつぎょう」と読みます。意味：毕业",
    source:"N2真题 2016",
  },
  {
    id:69,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>それは単なる噂にすぎない。",
    options:["〜に沿って", "〜にすぎない", "〜に比べて", "〜に基づいて"],
    answer: 1,
    explanation:"「〜にすぎない」：只不过是〜；不过是〜",
    source:"N2真题 2014",
  },
  {
    id:70,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「能力」",
    options:["のうりょく", "えんげき", "くいき", "とかい"],
    answer: 0,
    explanation:"「能力」は「のうりょく」と読みます。意味：能力",
    source:"N2真题 2017",
  },
  {
    id:71,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>業務プロセスを（  ）した。",
    options:["出生率", "改善", "符号", "注文"],
    answer: 1,
    explanation:"「改善」：改善",
    source:"N2真题 2023",
  },
  {
    id:72,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）市場が不安定だ。",
    options:["調査", "取得", "経営学", "金融"],
    answer: 3,
    explanation:"「金融」：金融",
    source:"N2真题 2011",
  },
  {
    id:73,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「参考」",
    options:["さんこう", "じっし", "しゅよう", "こうふく"],
    answer: 0,
    explanation:"「参考」は「さんこう」と読みます。意味：参考",
    source:"N2真题 2015",
  },
  {
    id:74,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「食事」",
    options:["ぐたい", "しょくじ", "こうしょう", "ほさ"],
    answer: 1,
    explanation:"「食事」は「しょくじ」と読みます。意味：餐饭；吃饭",
    source:"N2真题 2017",
  },
  {
    id:75,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「科学」",
    options:["しょくじ", "きんちょう", "かがく", "ぶんせき"],
    answer: 2,
    explanation:"「科学」は「かがく」と読みます。意味：科学",
    source:"N2真题 2022",
  },
  {
    id:76,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「価値」",
    options:["ちょくせつ", "かんどう", "かち", "しゅちょう"],
    answer: 2,
    explanation:"「価値」は「かち」と読みます。意味：价值",
    source:"N2真题 2020",
  },
  {
    id:77,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「基礎」",
    options:["ちゅうもん", "きそ", "つうしん", "しょり"],
    answer: 1,
    explanation:"「基礎」は「きそ」と読みます。意味：基础",
    source:"N2真题 2014",
  },
  {
    id:78,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>面接前は（  ）する。",
    options:["評価", "総合", "温室効果", "緊張"],
    answer: 3,
    explanation:"「緊張」：紧张",
    source:"N2真题 2019",
  },
  {
    id:79,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>日本語能力試験の（  ）を取った。",
    options:["配分", "認識", "資格", "自発"],
    answer: 2,
    explanation:"「資格」：资格",
    source:"N2真题 2015",
  },
  {
    id:80,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>新製品を（  ）する。",
    options:["論理", "開発", "主張", "機構"],
    answer: 1,
    explanation:"「開発」：开发",
    source:"N2真题 2023",
  },
  {
    id:81,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）を習得する。",
    options:["技術", "補佐", "支援", "演劇"],
    answer: 0,
    explanation:"「技術」：技术",
    source:"N2真题 2021",
  },
  {
    id:82,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>ボランティアを通じて多くを学んだ。",
    options:["〜かねる", "〜に基づいて", "〜を通じて（通して）", "〜にすぎない"],
    answer: 2,
    explanation:"「〜を通じて（通して）」：通过〜；经由〜",
    source:"N2真题 2015",
  },
  {
    id:83,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）は重要だ。",
    options:["幸福", "教育", "実施", "都会"],
    answer: 1,
    explanation:"「教育」：教育",
    source:"N2真题 2019",
  },
  {
    id:84,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「矛盾」",
    options:["れきし", "むじゅん", "ひんしつ", "ひとびと"],
    answer: 1,
    explanation:"「矛盾」は「むじゅん」と読みます。意味：矛盾",
    source:"N2真题 2017",
  },
  {
    id:85,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「緊張」",
    options:["きんちょう", "つたえる", "へる", "かんきょう"],
    answer: 0,
    explanation:"「緊張」は「きんちょう」と読みます。意味：紧张",
    source:"N2真题 2011",
  },
  {
    id:86,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>能力に加えて、努力も必要だ。",
    options:["〜かねる", "〜に加えて", "〜ほど", "〜ことから"],
    answer: 1,
    explanation:"「〜に加えて」：除〜之外还〜；加上〜",
    source:"N2真题 2017",
  },
  {
    id:87,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>世界が（  ）している。",
    options:["注目", "疲れる", "反映", "物理"],
    answer: 0,
    explanation:"「注目」：注目；关注",
    source:"N2真题 2014",
  },
  {
    id:88,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>彼は5年日本に住んでいたわけだから、日本語が上手だ。",
    options:["〜にすぎない", "〜から見ると", "〜わけだ", "〜に加えて"],
    answer: 2,
    explanation:"「〜わけだ」：难怪〜；所以〜（理所当然）",
    source:"N2真题 2015",
  },
  {
    id:89,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「利益」",
    options:["かわく", "りかい", "りえき", "じょうきょう"],
    answer: 2,
    explanation:"「利益」は「りえき」と読みます。意味：利益；利润",
    source:"N2真题 2015",
  },
  {
    id:90,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>彼は先生な（  ）タメ口だ。",
    options:["越える", "コミュニケーション", "法律", "のに"],
    answer: 3,
    explanation:"「のに」：明明～却～（逆接）",
    source:"N2真题 2021",
  },
  {
    id:91,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「参考」",
    options:["じょうきょう", "さんこう", "ばしょ", "あんぜん"],
    answer: 1,
    explanation:"「参考」は「さんこう」と読みます。意味：参考",
    source:"N2真题 2013",
  },
  {
    id:92,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「準備」",
    options:["かせぐ", "かかえる", "しっぱい", "じゅんび"],
    answer: 3,
    explanation:"「準備」は「じゅんび」と読みます。意味：准备",
    source:"N2真题 2018",
  },
  {
    id:93,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>新しい（  ）を勉強する。",
    options:["目的", "保存", "技術", "政治"],
    answer: 2,
    explanation:"「技術」：技术",
    source:"N2真题 2017",
  },
  {
    id:94,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>結果を（  ）してください。",
    options:["情熱", "程度", "芸術", "報告"],
    answer: 3,
    explanation:"「報告」：报告",
    source:"N2真题 2016",
  },
  {
    id:95,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）をはっきりさせる。",
    options:["政治", "反対", "比率", "目的"],
    answer: 3,
    explanation:"「目的」：目的",
    source:"N2真题 2022",
  },
  {
    id:96,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>この概念は（  ）しにくい。",
    options:["理解", "平和", "現象", "コミュニケーション"],
    answer: 0,
    explanation:"「理解」：理解",
    source:"N2真题 2019",
  },
  {
    id:97,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>無理をすると体を壊しかねない。",
    options:["〜にしても", "〜てならない", "〜から見ると", "〜かねない"],
    answer: 3,
    explanation:"「〜かねない」：说不定会〜（负面可能性）",
    source:"N2真题 2014",
  },
  {
    id:98,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「連絡」",
    options:["こくふく", "はじめる", "よくぼう", "れんらく"],
    answer: 3,
    explanation:"「連絡」は「れんらく」と読みます。意味：联系",
    source:"N2真题 2022",
  },
  {
    id:99,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「社会」",
    options:["あう", "しゃかい", "しかたがない", "めんどう"],
    answer: 1,
    explanation:"「社会」は「しゃかい」と読みます。意味：社会",
    source:"N2真题 2018",
  },
  {
    id:100,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>その条件には承諾しかねます。",
    options:["〜によると", "〜ずに（は）いられない", "〜さえ〜ば", "〜かねる"],
    answer: 3,
    explanation:"「〜かねる」：难以〜；不能〜（无法接受）",
    source:"N2真题 2014",
  },
  {
    id:101,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>試験が心配でたまらない。",
    options:["〜にもかかわらず", "〜てたまらない", "〜に対して", "〜にほかならない"],
    answer: 1,
    explanation:"「〜てたまらない」：〜得不得了；极其〜",
    source:"N2真题 2014",
  },
  {
    id:102,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「技術」",
    options:["しゃかい", "だきょう", "ふほうわ", "ぎじゅつ"],
    answer: 3,
    explanation:"「技術」は「ぎじゅつ」と読みます。意味：技术",
    source:"N2真题 2018",
  },
  {
    id:103,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>故郷が懐かしくてならない。",
    options:["〜にもかかわらず", "〜ことにしている", "〜てならない", "〜に加えて"],
    answer: 2,
    explanation:"「〜てならない」：非常〜；不由得〜",
    source:"N2真题 2019",
  },
  {
    id:104,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「教育」",
    options:["こうきょう", "きょういく", "おどろく", "さがす"],
    answer: 1,
    explanation:"「教育」は「きょういく」と読みます。意味：教育",
    source:"N2真题 2021",
  },
  {
    id:105,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>健康の上で大切なことを話した。",
    options:["〜とともに", "〜ではないか", "〜からといって", "〜上で"],
    answer: 3,
    explanation:"「〜上で」：在〜方面；做〜之后",
    source:"N2真题 2016",
  },
  {
    id:106,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>新製品の（  ）が進んでいる。",
    options:["開発", "情熱", "支払う", "妥協"],
    answer: 0,
    explanation:"「開発」：开发",
    source:"N2真题 2022",
  },
  {
    id:107,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「連絡」",
    options:["びょうどう", "おんど", "れんらく", "かせぐ"],
    answer: 2,
    explanation:"「連絡」は「れんらく」と読みます。意味：联系",
    source:"N2真题 2014",
  },
  {
    id:108,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「決定」",
    options:["けってい", "りょこう", "えんぜつ", "やぶる"],
    answer: 0,
    explanation:"「決定」は「けってい」と読みます。意味：决定",
    source:"N2真题 2016",
  },
  {
    id:109,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>彼女は美人の上に、頭もいい。",
    options:["〜を通じて（通して）", "〜ことにしている", "〜というより", "〜上に"],
    answer: 3,
    explanation:"「〜上に」：不仅〜，而且〜（程度追加）",
    source:"N2真题 2020",
  },
  {
    id:110,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「社会」",
    options:["げんいん", "むく", "きもち", "しゃかい"],
    answer: 3,
    explanation:"「社会」は「しゃかい」と読みます。意味：社会",
    source:"N2真题 2015",
  },
  {
    id:111,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「社会」",
    options:["はんえい", "しんぶん", "しゃかい", "つかれる"],
    answer: 2,
    explanation:"「社会」は「しゃかい」と読みます。意味：社会",
    source:"N2真题 2010",
  },
  {
    id:112,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「生活」",
    options:["ほうりつ", "びょうどう", "せいかつ", "のぞむ"],
    answer: 2,
    explanation:"「生活」は「せいかつ」と読みます。意味：生活",
    source:"N2真题 2018",
  },
  {
    id:113,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「仕事」",
    options:["たすける", "じょうきょう", "かんきょう", "しごと"],
    answer: 3,
    explanation:"「仕事」は「しごと」と読みます。意味：工作",
    source:"N2真题 2021",
  },
  {
    id:114,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>深く（  ）。",
    options:["考える", "相談", "情報", "探す"],
    answer: 0,
    explanation:"「考える」：思考",
    source:"N2真题 2011",
  },
  {
    id:115,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「考える」",
    options:["きょうそう", "かんがえる", "えいきょう", "つかれる"],
    answer: 1,
    explanation:"「考える」は「かんがえる」と読みます。意味：思考",
    source:"N2真题 2017",
  },
  {
    id:116,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>彼ほど優秀な学生はいない。",
    options:["〜に際して", "〜に沿って", "〜ほど", "〜上で"],
    answer: 2,
    explanation:"「〜ほど」：越〜越〜；〜得…程度",
    source:"N2真题 2014",
  },
  {
    id:117,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「楽しみ」",
    options:["たのしみ", "あんぜん", "さんそ", "はげます"],
    answer: 0,
    explanation:"「楽しみ」は「たのしみ」と読みます。意味：乐趣；期待",
    source:"N2真题 2021",
  },
  {
    id:118,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>お金さえあれば、何でもできる。",
    options:["〜さえ〜ば", "〜に関して", "〜せいで", "〜に沿って"],
    answer: 0,
    explanation:"「〜さえ〜ば」：只要〜就行了",
    source:"N2真题 2017",
  },
  {
    id:119,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>困難にもかかわらず、諦めなかった。",
    options:["〜にもかかわらず", "〜てたまらない", "〜に対し", "〜から見ると"],
    answer: 0,
    explanation:"「〜にもかかわらず」：即便〜也；尽管〜",
    source:"N2真题 2013",
  },
  {
    id:120,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>時間の経過とともに、悲しみが薄れた。",
    options:["〜というより", "〜とともに", "〜に反して", "〜をはじめ（として）"],
    answer: 1,
    explanation:"「〜とともに」：和〜一起；随着〜",
    source:"N2真题 2016",
  },
  {
    id:121,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）を満たしている。",
    options:["計算", "区別", "温室効果", "基準"],
    answer: 3,
    explanation:"「基準」：标准；基准",
    source:"N2真题 2012",
  },
  {
    id:122,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>年齢に関わらず、参加できます。",
    options:["〜さえ〜ば", "〜にほかならない", "〜に関わらず", "〜てたまらない"],
    answer: 2,
    explanation:"「〜に関わらず」：不管〜；无论〜",
    source:"N2真题 2010",
  },
  {
    id:123,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>3時間にわたって会議が続いた。",
    options:["〜に際して", "〜にわたって", "〜として", "〜によると"],
    answer: 1,
    explanation:"「〜にわたって」：长达〜（时间/范围延续）",
    source:"N2真题 2022",
  },
  {
    id:124,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「管理」",
    options:["ふごう", "かんり", "じっし", "きょうちょう"],
    answer: 1,
    explanation:"「管理」は「かんり」と読みます。意味：管理",
    source:"N2真题 2023",
  },
  {
    id:125,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>試験（  ）は一週間だ。",
    options:["傾向", "処理", "期間", "支店"],
    answer: 2,
    explanation:"「期間」：期间",
    source:"N2真题 2013",
  },
  {
    id:126,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「権利」",
    options:["ちい", "よそく", "けんり", "とかい"],
    answer: 2,
    explanation:"「権利」は「けんり」と読みます。意味：权利",
    source:"N2真题 2017",
  },
  {
    id:127,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>彼の（  ）を鑑賞する。",
    options:["勧告", "液体", "作品", "目標"],
    answer: 2,
    explanation:"「作品」：作品",
    source:"N2真题 2015",
  },
  {
    id:128,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>電話で（  ）が入った。",
    options:["協力", "局限", "注文", "処理"],
    answer: 2,
    explanation:"「注文」：订购；点餐",
    source:"N2真题 2011",
  },
  {
    id:129,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「直接」",
    options:["げんじつ", "ちょくせつ", "しゅちょう", "しどうしゃ"],
    answer: 1,
    explanation:"「直接」は「ちょくせつ」と読みます。意味：直接",
    source:"N2真题 2020",
  },
  {
    id:130,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>去年に比べて、今年は暑い。",
    options:["〜に比べて", "〜てならない", "〜ほど", "〜として"],
    answer: 0,
    explanation:"「〜に比べて」：与〜相比",
    source:"N2真题 2017",
  },
  {
    id:131,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>東京をはじめ、大阪、名古屋も有名だ。",
    options:["〜せいで", "〜おかげで", "〜をはじめ（として）", "〜に沿って"],
    answer: 2,
    explanation:"「〜をはじめ（として）」：以〜为首；〜等",
    source:"N2真题 2017",
  },
  {
    id:132,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）での生活に慣れた。",
    options:["反応", "単位", "都会", "楽しみ"],
    answer: 2,
    explanation:"「都会」：都市；城市",
    source:"N2真题 2016",
  },
  {
    id:133,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>外国人から見ると、日本の習慣は独特だ。",
    options:["〜から見ると", "〜に加えて", "〜に比べて", "〜に基づいて"],
    answer: 0,
    explanation:"「〜から見ると」：从〜来看；从〜角度看",
    source:"N2真题 2019",
  },
  {
    id:134,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）暖かくなってきた。",
    options:["冊数", "情報", "分析", "だんだん"],
    answer: 3,
    explanation:"「だんだん」：渐渐",
    source:"N2真题 2013",
  },
  {
    id:135,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>問題の（  ）を共有する。",
    options:["認識", "社会学", "反応", "初歩"],
    answer: 0,
    explanation:"「認識」：认识；认知",
    source:"N2真题 2010",
  },
  {
    id:136,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「運営」",
    options:["えきたい", "ほさ", "うんえい", "りろん"],
    answer: 2,
    explanation:"「運営」は「うんえい」と読みます。意味：运营；经营",
    source:"N2真题 2012",
  },
  {
    id:137,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「競争」",
    options:["がいねん", "たんとうしゃ", "ふきゅう", "きょうそう"],
    answer: 3,
    explanation:"「競争」は「きょうそう」と読みます。意味：竞争",
    source:"N2真题 2022",
  },
  {
    id:138,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>教師として、学生に責任がある。",
    options:["〜かねる", "〜において", "〜として", "〜をはじめ（として）"],
    answer: 2,
    explanation:"「〜として」：作为〜；以〜身份",
    source:"N2真题 2023",
  },
  {
    id:139,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「採用」",
    options:["ろんり", "しょり", "さいよう", "たいりょう"],
    answer: 2,
    explanation:"「採用」は「さいよう」と読みます。意味：采用；录用",
    source:"N2真题 2018",
  },
  {
    id:140,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）を大切に使おう。",
    options:["資源", "主要", "だんだん", "熱意"],
    answer: 0,
    explanation:"「資源」：资源",
    source:"N2真题 2010",
  },
  {
    id:141,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>パソコンの（  ）をチェックする。",
    options:["返事", "状態", "環境", "地位"],
    answer: 1,
    explanation:"「状態」：状态",
    source:"N2真题 2020",
  },
  {
    id:142,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「処理」",
    options:["しょり", "けいえいがく", "りっしょう", "かしゅ"],
    answer: 0,
    explanation:"「処理」は「しょり」と読みます。意味：处理",
    source:"N2真题 2011",
  },
  {
    id:143,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）制度を改革する。",
    options:["決心", "規律", "新鮮", "医療"],
    answer: 3,
    explanation:"「医療」：医疗",
    source:"N2真题 2016",
  },
  {
    id:144,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）の事情で欠席する。",
    options:["家庭", "信頼", "届く", "論理"],
    answer: 0,
    explanation:"「家庭」：家庭",
    source:"N2真题 2013",
  },
  {
    id:145,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「記憶」",
    options:["かいぜん", "ようてん", "てんらんかい", "きおく"],
    answer: 3,
    explanation:"「記憶」は「きおく」と読みます。意味：记忆",
    source:"N2真题 2010",
  },
  {
    id:146,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>批判に対し、説明した。",
    options:["〜をはじめ（として）", "〜ものだ", "〜に対し", "〜ではないか"],
    answer: 2,
    explanation:"「〜に対し」：对于〜；针对〜（书面简洁形）",
    source:"N2真题 2010",
  },
  {
    id:147,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「 May 甚至」",
    options:["しんぽ", "かのう", "きおく", "さえ"],
    answer: 3,
    explanation:"「 May 甚至」は「さえ」と読みます。意味：甚至；连～都",
    source:"N2真题 2019",
  },
  {
    id:148,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「信頼」",
    options:["かのうせい", "ちゅうもん", "しんらい", "きたい"],
    answer: 2,
    explanation:"「信頼」は「しんらい」と読みます。意味：信赖",
    source:"N2真题 2018",
  },
  {
    id:149,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「都合」",
    options:["つごう", "こうしょう", "にんむ", "げんいん"],
    answer: 0,
    explanation:"「都合」は「つごう」と読みます。意味：情况；方便程度",
    source:"N2真题 2019",
  },
  {
    id:150,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「役割」",
    options:["ろんり", "いはん", "はげます", "やくわり"],
    answer: 3,
    explanation:"「役割」は「やくわり」と読みます。意味：作用；角色",
    source:"N2真题 2021",
  },
  {
    id:151,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>時間が経つのは早いものだ。",
    options:["〜一方だ", "〜ものだ", "〜さえ〜ば", "〜に対して"],
    answer: 1,
    explanation:"「〜ものだ」：本来〜；（感慨）真是〜啊",
    source:"N2真题 2021",
  },
  {
    id:152,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>急いでいたものだから、忘れてしまった。",
    options:["〜にしても", "〜てたまらない", "〜に沿って", "〜ものだから"],
    answer: 3,
    explanation:"「〜ものだから」：因为〜（辩解·解释原因）",
    source:"N2真题 2010",
  },
  {
    id:153,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>要求に応じて、計画を変えた。",
    options:["〜にもかかわらず", "〜から見ると", "〜ものだ", "〜に応じて"],
    answer: 3,
    explanation:"「〜に応じて」：根据〜；按照〜",
    source:"N2真题 2011",
  },
  {
    id:154,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>調査（  ）を広げる。",
    options:["範囲", "符号", "進歩", "進歩"],
    answer: 0,
    explanation:"「範囲」：范围",
    source:"N2真题 2019",
  },
  {
    id:155,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>旅行を通して、多くの文化を学んだ。",
    options:["〜を通して", "〜に沿って", "〜に反して", "〜かねない"],
    answer: 0,
    explanation:"「〜を通して」：通过〜（整个过程/媒介）",
    source:"N2真题 2011",
  },
  {
    id:156,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>合格の（  ）を満たす。",
    options:["欠点", "疾病", "実践", "基準"],
    answer: 3,
    explanation:"「基準」：标准",
    source:"N2真题 2013",
  },
  {
    id:157,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>皆で（  ）して仕事をする。",
    options:["実施", "安全", "抽象", "協力"],
    answer: 3,
    explanation:"「協力」：合作",
    source:"N2真题 2015",
  },
  {
    id:158,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>仕事の（  ）をする。",
    options:["背景", "評価", "辛い", "心理学"],
    answer: 1,
    explanation:"「評価」：评价",
    source:"N2真题 2011",
  },
  {
    id:159,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「目標」",
    options:["かんきょう", "もくひょう", "ほんしつ", "いよく"],
    answer: 1,
    explanation:"「目標」は「もくひょう」と読みます。意味：目标",
    source:"N2真题 2016",
  },
  {
    id:160,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>データを（  ）する。",
    options:["定義", "競争", "分析", "要因"],
    answer: 2,
    explanation:"「分析」：分析",
    source:"N2真题 2012",
  },
  {
    id:161,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「研究」",
    options:["ちゅうもん", "きょうきゅう", "かくだい", "けんきゅう"],
    answer: 3,
    explanation:"「研究」は「けんきゅう」と読みます。意味：研究",
    source:"N2真题 2019",
  },
  {
    id:162,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「分析」",
    options:["しあわせ", "けいざい", "しゅっぱん", "ぶんせき"],
    answer: 3,
    explanation:"「分析」は「ぶんせき」と読みます。意味：分析",
    source:"N2真题 2015",
  },
  {
    id:163,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）を達成した。",
    options:["実践", "設定", "目標", "進化"],
    answer: 2,
    explanation:"「目標」：目标",
    source:"N2真题 2021",
  },
  {
    id:164,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>成功は努力の結果にほかならない。",
    options:["〜に関わらず", "〜ことにしている", "〜にもかかわらず", "〜にほかならない"],
    answer: 3,
    explanation:"「〜にほかならない」：无非是〜；正是〜",
    source:"N2真题 2014",
  },
  {
    id:165,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>「一期一会」というのは、一生に一度の出会いという意味だ。",
    options:["〜というのは", "〜かねる", "〜ようとする", "〜に関して"],
    answer: 0,
    explanation:"「〜というのは」：所谓〜是指；〜这件事",
    source:"N2真题 2012",
  },
  {
    id:166,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>苦手を（  ）して成績が伸びた。",
    options:["重視", "公共", "会う", "克服"],
    answer: 3,
    explanation:"「克服」：克服",
    source:"N2真题 2017",
  },
  {
    id:167,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「曖昧」",
    options:["こころみる", "きえる", "あいまい", "あつめる"],
    answer: 2,
    explanation:"「曖昧」は「あいまい」と読みます。意味：暧昧；模糊",
    source:"N2真题 2011",
  },
  {
    id:168,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「重視」",
    options:["じゅうし", "あんぜん", "かんがえる", "しゃかい"],
    answer: 0,
    explanation:"「重視」は「じゅうし」と読みます。意味：重视",
    source:"N2真题 2019",
  },
  {
    id:169,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「不可欠」",
    options:["しょうめい", "ふかけつ", "きんちょう", "ひつようせい"],
    answer: 1,
    explanation:"「不可欠」は「ふかけつ」と読みます。意味：不可或缺",
    source:"N2真题 2011",
  },
  {
    id:170,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「段階」",
    options:["せつやく", "せんもん", "だんかい", "りえき"],
    answer: 2,
    explanation:"「段階」は「だんかい」と読みます。意味：阶段",
    source:"N2真题 2011",
  },
  {
    id:171,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）100人が参加した。",
    options:["調べる", "資源", "越える", "約"],
    answer: 3,
    explanation:"「約」：大约；约定",
    source:"N2真题 2019",
  },
  {
    id:172,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「提案」",
    options:["かわく", "げんしょう", "ていあん", "しょき"],
    answer: 2,
    explanation:"「提案」は「ていあん」と読みます。意味：提案；建议",
    source:"N2真题 2015",
  },
  {
    id:173,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>この作業は（  ）だ。",
    options:["困難", "コミュニケーション", "発展", "張る"],
    answer: 0,
    explanation:"「困難」：困难",
    source:"N2真题 2013",
  },
  {
    id:174,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「資格」",
    options:["せつめい", "いけん", "そうい", "しかく"],
    answer: 3,
    explanation:"「資格」は「しかく」と読みます。意味：资格",
    source:"N2真题 2013",
  },
  {
    id:175,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>英語が話せるからといって、仕事ができるとは限らない。",
    options:["〜ものだから", "〜に反して", "〜からといって", "〜というより"],
    answer: 2,
    explanation:"「〜からといって」：不能因为〜就〜（驳斥以偏概全）",
    source:"N2真题 2015",
  },
  {
    id:176,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「取得」",
    options:["どりょく", "のぼる", "まねく", "しゅとく"],
    answer: 3,
    explanation:"「取得」は「しゅとく」と読みます。意味：取得；获得",
    source:"N2真题 2014",
  },
  {
    id:177,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>日本の（  ）が減っている。",
    options:["人口", "温度", "任せる", "展開"],
    answer: 0,
    explanation:"「人口」：人口",
    source:"N2真题 2022",
  },
  {
    id:178,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>結果に（  ）している。",
    options:["程度", "期待", "芸術", "購入"],
    answer: 1,
    explanation:"「期待」：期待",
    source:"N2真题 2012",
  },
  {
    id:179,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>この製品の（  ）はデザインだ。",
    options:["初期", "科学", "解析", "特徴"],
    answer: 3,
    explanation:"「特徴」：特征；特点",
    source:"N2真题 2015",
  },
  {
    id:180,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「平和」",
    options:["けす", "へいわ", "つきあう", "まよう"],
    answer: 1,
    explanation:"「平和」は「へいわ」と読みます。意味：和平",
    source:"N2真题 2023",
  },
  {
    id:181,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>レストランを（  ）した。",
    options:["理解", "予約", "背景", "乗り換える"],
    answer: 1,
    explanation:"「予約」：预约",
    source:"N2真题 2022",
  },
  {
    id:182,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>会社の（  ）を増やす。",
    options:["伝える", "依頼", "利益", "普及"],
    answer: 2,
    explanation:"「利益」：利益；利润",
    source:"N2真题 2010",
  },
  {
    id:183,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>日本（  ）に興味がある。",
    options:["文化", "趣味", "社会", "運営"],
    answer: 0,
    explanation:"「文化」：文化",
    source:"N2真题 2021",
  },
  {
    id:184,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「交通」",
    options:["しはらう", "せんそう", "こころみる", "こうつう"],
    answer: 3,
    explanation:"「交通」は「こうつう」と読みます。意味：交通",
    source:"N2真题 2014",
  },
  {
    id:185,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「政治」",
    options:["のぞむ", "せいじ", "ほうりつ", "しんじる"],
    answer: 1,
    explanation:"「政治」は「せいじ」と読みます。意味：政治",
    source:"N2真题 2015",
  },
  {
    id:186,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>新しい（  ）が始まった。",
    options:["不饱和", "人口", "制度", "科学"],
    answer: 2,
    explanation:"「制度」：制度",
    source:"N2真题 2011",
  },
  {
    id:187,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>市場（  ）を行った。",
    options:["沈む", "育てる", "論文", "調査"],
    answer: 3,
    explanation:"「調査」：调查",
    source:"N2真题 2014",
  },
  {
    id:188,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「報告」",
    options:["ほうこく", "おわる", "じゅんび", "こうじょう"],
    answer: 0,
    explanation:"「報告」は「ほうこく」と読みます。意味：报告",
    source:"N2真题 2018",
  },
  {
    id:189,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>失敗したにしても、諦めてはいけない。",
    options:["〜ものだ", "〜に加えて", "〜わけだ", "〜にしても"],
    answer: 3,
    explanation:"「〜にしても」：即使〜也；就算〜也",
    source:"N2真题 2013",
  },
  {
    id:190,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「判断」",
    options:["かんどう", "ひつようせい", "はんだん", "こえる"],
    answer: 2,
    explanation:"「判断」は「はんだん」と読みます。意味：判断",
    source:"N2真题 2020",
  },
  {
    id:191,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>（  ）があれば聞いてください。",
    options:["製造", "説明", "商品", "質問"],
    answer: 3,
    explanation:"「質問」：问题；提问",
    source:"N2真题 2023",
  },
  {
    id:192,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>卒業にあたって、先生に感謝した。",
    options:["〜にしても", "〜として", "〜にあたって", "〜に加えて"],
    answer: 2,
    explanation:"「〜にあたって」：在〜之际；值〜之时",
    source:"N2真题 2020",
  },
  {
    id:193,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>入社に際して、研修を受けた。",
    options:["〜に際して", "〜にもかかわらず", "〜に比べて", "〜をはじめ（として）"],
    answer: 0,
    explanation:"「〜に際して」：在〜之际（正式场合）",
    source:"N2真题 2014",
  },
  {
    id:194,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>留学を契機に、人生が変わった。",
    options:["〜を通じて（通して）", "〜おかげで", "〜を契機に", "〜ことなく"],
    answer: 2,
    explanation:"「〜を契機に」：以〜为契机",
    source:"N2真题 2017",
  },
  {
    id:195,
    level:"n2",
    type:"vocab",
    question:"【語彙】次の文の（  ）に入る最もよいものを選びなさい。<br>公共施設を（  ）する。",
    options:["保存", "利用", "文化", "支払う"],
    answer: 1,
    explanation:"「利用」：利用",
    source:"N2真题 2022",
  },
  {
    id:196,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>好きかといえば、好きではない。",
    options:["〜かねない", "〜に沿って", "〜ほど", "〜かといえば"],
    answer: 3,
    explanation:"「〜かといえば」：说起〜的话；要说是否〜",
    source:"N2真题 2021",
  },
  {
    id:197,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>あの映画を見て、泣かずにはいられなかった。",
    options:["〜に基づいて", "〜ものだ", "〜上で", "〜ずに（は）いられない"],
    answer: 3,
    explanation:"「〜ずに（は）いられない」：不得不〜；忍不住〜",
    source:"N2真题 2017",
  },
  {
    id:198,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>怒っているというより、悲しんでいる。",
    options:["〜ものの", "〜てたまらない", "〜というより", "〜ようとする"],
    answer: 2,
    explanation:"「〜というより」：与其说〜不如说",
    source:"N2真题 2015",
  },
  {
    id:199,
    level:"n2",
    type:"vocab",
    question:"【文字語彙】次の言葉の読み方として最もよいものを選びなさい。<br>「努力」",
    options:["とくちょう", "しょくどう", "どりょく", "はいけい"],
    answer: 2,
    explanation:"「努力」は「どりょく」と読みます。意味：努力",
    source:"N2真题 2011",
  },
  {
    id:200,
    level:"n2",
    type:"grammar",
    question:"【文法】次の文の（  ）に入る最もよいものを選びなさい。<br>予想に反して、試験が難しかった。",
    options:["〜に反して", "〜に基づいて", "〜によると", "〜ずに（は）いられない"],
    answer: 0,
    explanation:"「〜に反して」：与〜相反；违背〜",
    source:"N2真题 2014",
  },
];
